### ISSUE TITLE
Domain names in the WHMCS invoices

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#1]
Is it possible to insert the domain names in the WHMCS invoices? https://screencast.com/t/KRNA6z8efpd

**Comment by ggs-victor** [comment]
We appreciate your suggestion. It was routed to our developers, they will implement the feature if that is technically possible within WHMCS

**Comment by ggs-victor** [comment]
Feature added with [1.0.33 release](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.33)
