### ISSUE TITLE
SSL Orders Summary not working

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#10]
**Describe the bug**
The 'SSL Orders Summary' is showing all zeros except for Total Orders

**To Reproduce**
1. Go to WHMCS Client Area.
2. Click on Services
3. Scroll down to 'SSL Orders Summary'
4. See error;

SSL Orders Summary
204 Total Orders
0 Unpaid Orders
0 Processing
0 Expires Soon

**Expected behavior**
This user has many Expiring soon, and around 7 Processing. 

**Screenshots**
Is this public? 

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
It seems only the total number of orders is working

**Comment by vlad-evg** [comment]
Dear Customer,

have you set CRON job for that as described here?
https://github.com/gogetssl/whmcs-addon/wiki/Orders-Summary

**Comment by qhgh** [comment]
Thanks, running `php -q /var/www/whmcs/modules/addons/GGSSLWHMCS/cron/certificateStatsLoader.php` has fixed the issue.

Just a note: it would be nice if clicking on these headings, it showed the sorted SSLs for the heading that was clicked:

**SSL Orders Summary**
204 Total Orders >> works ok / shows all ssl
0 Unpaid Orders >> does not show unpaid, it shows all ssl
0 Processing >> does not show processing, it shows all ssl 
0 Expires Soon >> does not show expiring, it shows all ssl

**Comment by qhgh** [comment]
Also, one more suggestion, it would good if the 'SSL Orders Summary' was only shown to clients who actually have SSL orders. Thanks for the help in resolving the original issue. :)

**Comment by vlad-evg** [comment]
> Just a note: it would be nice if clicking on these headings, it showed the sorted SSLs for the heading that was clicked:

Yes, we would try to do that, if WHMCS can handle it, then our addon would have it.

> Also, one more suggestion, it would good if the 'SSL Orders Summary' was only shown to clients who actually have SSL orders. Thanks for the help in resolving the original issue. :)

We would try to do that too. 
We are checking that options now.

**Comment by qhgh** [comment]
Thanks for the update :+1:

**Comment by vlad-evg** [comment]
Both features will be released within few days in 1.0.40 package
