### ISSUE TITLE
Allow us to choose which pages the sidebar is displayed on

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#102]
It would be great to have the option to select which pages the SSLCenter Sidebar is shown on.
At the moment, the sidebar seems to display on all pages in the client area besides clientareahome.

Currently, it is done like this:
```
if (in_array($smarty->tpl_vars['templatefile']->value, array('clientareahome')) || !isset($_SESSION['uid']))
        return;
``` 
I'm suggesting that a field is created to input the comma-separated list of templatefiles where you want to/don't want to show the sidebar. That way, the current code will need very minor tweaks.

**Comment by vlad-evg** [comment]
We will implement that to the next release

**Comment by vlad-evg** [comment]
Implemented in latest [release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.3.3). Than you for suggestion
