### ISSUE TITLE
APIProcessingOrders.php missing

### ISSUE THREAD

**Issue by pyrateby** [gogetssl/whmcs-addon#103]
**Describe the bug**

**To Reproduce**
1. whmcs admin> addons>sslcenter whmcs
2. and here it an cron job command modules/addons/SSLCENTERWHMCS/cron/APIProcessingOrders.php
**Expected behavior**
but in that folder that file for cron job it missing, so this command for cron job it uselles

**Screenshots**
https://prnt.sc/r491qt

**Comment by vlad-evg** [comment]
We would urgently recheck that

**Comment by pyrateby** [comment]
tank you

**Comment by DennisSkov** [comment]
It seems to not be the only file missing. APIDailyStatusUpdater.php is also missing.

**Comment by pyrateby** [comment]
> It seems to not be the only file missing. APIDailyStatusUpdater.php is also missing.

you right, i missed that file, didnt see

**Comment by cenourinha** [comment]
I also already noted the missing of this file.

**Comment by vlad-evg** [comment]
There was an error with the merging master repository. Now all files available in the [latest release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.3.2d)
