### ISSUE TITLE
Certificate  File Download

### ISSUE THREAD

**Issue by chinalujw** [gogetssl/whmcs-addon#104]
Currently, certificate files are provided on the website in code form, and download (including email notification) is expected to be provided in file form.  Like The form of the my.gogetssl.com website.

**Comment by vlad-evg** [comment]
You want to download SSL certificates via button?

**Comment by chinalujw** [comment]
Yes，and Sending mail is also in the form of file attachments.

**Comment by vlad-evg** [comment]
Implemented in latest [release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.3.3). Than you for suggestion

**Comment by chinalujw** [comment]
Thanks.
