### ISSUE TITLE
WHMCS cannot make a 2 year SSL when set to 'one time' pricing

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#11]
**Describe the bug**
We have an issue where we have a 2 type of customer.

1. Customers do not want auto-renew SSL
2. Customers do want auto-renew SSL

**To Reproduce**
1. Go to place a new SSL order
2. Click on 2 year / biennially 
3. Complete the order
4. See error > the SSL order is placed for 12 months, not 24 months.

**Expected behavior**
The SSL order should be placed for 24 months. 

**Screenshots**
Is this public?

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
We are not clear how auto-renew SSL is working. If we allow GGSSL module to `Create automatical renewal invoice` then the customer gets double billed. One by WHMCS and one by GGSSL. The invoice look different, so it's clear which is from WHMCS and which is from GGSL.

If we set all SSL product to 'one time', billing is correct and no more double billing, but we cannot use 2 year SSL. 

We have raised this with GGSSL before, but it was never resolved. 

It would be great if we could set WHMCS to 'one time' (default do not renew) and let GGSSL module handle the auto-renew if customer chooses it.

Any help greatly appreciated. 

Thank you.

**Comment by qhgh** [comment]
Sorry, I'll try to be clear.

If the SSL products inside WHMCS are set to recurring, then WHMCS will make new invoice on renewal date, and so will the GGSSL module. So the customer gets double billed. 

If we set the SSL products inside WHMCS to one time pricing, then only your module makes invoice on renewal date, but then we cannot order more that 12 month SSL. It seems one time means one year.

We are using latest module :)

Thanks for advice.

**Comment by vlad-evg** [comment]
Yes, one-time has only 12 months max due to some technical limitations. However, that would be fixed within 7-8 weeks when we would release API 2.0

**Comment by ggs-victor** [comment]
The best option is to using recurring payment, in that case customer can order 2 year SSL, renewal would be also for 2 years with proper period and price. We have released [1.0.40](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.40), it has an update for that.
