### ISSUE TITLE
Problem with multiple currency

### ISSUE THREAD

**Issue by pyrateby** [gogetssl/whmcs-addon#111]
Hello, i just fount that i have a problem with ssl certificate.
So, on my website i have 2 currency EUR and RON
First problem: in addons>sslcenter whm>productsConfiguration on the pricing tab it show me the currency RON not EUR, and eur it the first and ron second.
Second problem: when i configure an ssl and it show me the Billing Cycle there it show the good price with commision but on Order Summary it show the price without the commision, and when it finish the order the customar as to pay the price without the commision.
All of this when it select the currency EUR
But when it select the currency RON it show evrey thing ok, on the billing cycle and rder summary it show the price with the commision.
I will put here some link's with screenshot to show u the problem.
https://prnt.sc/rbzb0o
https://prnt.sc/rbzb9v
https://prnt.sc/rbzbn6 currency EUR not good
https://prnt.sc/rbzbyj currency RON good

I whait for some answers and solution. Thank you.

**Comment by pyrateby** [comment]
Any ideeas?

**Comment by vlad-evg** [comment]
Hello, sorry for the delay.

Can you submit ticket via client area and provide Admin WHMCS access? We would check all your issues

**Comment by pyrateby** [comment]
Yes i will submit right now

**Comment by pyrateby** [comment]
any updates???
