### ISSUE TITLE
Renewal invoices have incorrect due date

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#112]
When a new renewal invoice for a SSL certificate is created, due date is the same date as invoice date.
In our example, this is 21-02-2020.
However - the certificate doesn't expire before 21-05-2020. Shouldn't the due date be set to this date as well?
Also, why are invoices created with the status "Payment Pending" instead of "Unpaid"?

**Comment by vlad-evg** [comment]
There is CRON, that should update expiration dates
https://github.com/gogetssl/whmcs-addon/wiki/CRON-Jobs#cron

We would check About payment status

**Comment by DennisSkov** [comment]
That cron job is already setup. 
Why isn't the due date just set correctly when creating the invoice?

**Comment by vlad-evg** [comment]
It is not possible to know what will be the expiration date of SSL until it will be issued

**Comment by DennisSkov** [comment]
Well, the cron job doesn't change the due date for us either :)
I've just tried running it manually, but nothing changed.

**Comment by vlad-evg** [comment]
Can you pass us WHMCS access via ticket? We would pass it to Modules garden to check

**Comment by DennisSkov** [comment]
I've sent in a ticket with login to WHMCS :)

**Comment by DennisSkov** [comment]
> It is not possible to know what will be the expiration date of SSL until it will be issued

Couldn't next due date just be set to what the Next Due Date field is set to for the product in WHMCS?

**Comment by vlad-evg** [comment]
Issued solved with [2.4.1 version](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.1)
