### ISSUE TITLE
Version still showing older

### ISSUE THREAD

**Issue by yashodhank** [gogetssl/whmcs-addon#114]
I think following value need to be updated to match with stable latest release version. 

https://github.com/gogetssl/whmcs-addon/blob/be21faee289fb3d04c67f741ea36b6c9fa62f07c/modules/addons/SSLCENTERWHMCS/Configuration.php#L56

**Comment by bady1985** [comment]
According to github, only the readme was updated in the last version, so it would have to change more than the version number ;), there was probably an error in the merge.

**Comment by vlad-evg** [comment]
Sorry guys! Yes, merge issues. Now fixed
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.1a
