### ISSUE TITLE
Save all

### ISSUE THREAD

**Issue by steinipe** [gogetssl/whmcs-addon#115]
It would be really cool if one could goto the Product Configuration, make all their edits at once, and then click Save all at the bottom, not having to save each product. I spent a lot of time in there and then hit Save on the last product, all my other changes were not made, I had to do everything 1 by 1.

PS: There is nothing in your WIKI about "Download pricing automatically", I had to uncheck this which was default checked so I could set my pricing, I assume this has something to do with the cron that downloads the pricing online but seems weird to have that default on.

**Comment by vlad-evg** [comment]
Yes, good comment. We will speak to developers if such button can be added. We also were clicking save for each product which is annoying.

**Comment by vlad-evg** [comment]
Feature released now in [v.2.4.4. release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.4)
