### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#117]
Hello,

After upgrading from 2.3.3 to the latest one, the regular dedicated ip, username and password fields are gone in product page in WHMCS admin area. I not find anything about this, maybe this is not a bug, or maybe it, can you check it please?

WHMCS version:  7.9.2

![screencapture-my-mikrovps-net-fonok-clientsservices-php-2020-04-07-21_05_09](https://user-images.githubusercontent.com/690503/78709436-f2056200-7913-11ea-9475-523ff51fcf19.png)

**Comment by vlad-evg** [comment]
Well, they are not required as the SSL should be managed via Client area. Have you used those fields before?

**Comment by charliehu** [comment]
I dont need, but bcs i not find anything abojt this in documentation, mayne it can be a bug. I never seen any module what remove these fields, even from any other module from ModuleaGarden.

And it broke the design in admin area.
