### ISSUE TITLE
Renewal button Issues

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#12]
**Describe the bug**
1. The Renewal Invoice is created based on the old SSL Certificate's price. During the SSL Certificate's lifetime, the price can change, therefore, when renewing the SSL Certificate, the module should pull up the current (the nowadays, existing price), not the last year's price of the SSL Certificate. 
How to fix this so that the invoice gets generated for the current SSL Certificate's price?

2. The invoice for a 2 year SSL Certificate states that it's renewed for 1 year, although it's price corresponds to 2 years. 
How to remove the period from the invoice or how to fix this so that it shows the right period?

3. What will happen when renewing a 3-year SSL Certificate (which have been removed from March 2018)? 

**Expected behavior**
1. The Renewal Invoice should contain the current SSL Certificate's price
2. The Renewal Invoice should not contain its period/should contain the right period
3. 3-year SSL Certificate shouldn't be able to be renewed/should be renewed with a 2-year SSL Certificate

**Comment by ggs-victor** [comment]
Dear Sergiurosca,

1. We would make that update/fix  to SSL add-on ASAP
2. We would fix that issue with next release
3. Good question, I think we would make update and renewal will be for the MAX period of 2 years

Thank you for all your suggestions/issues. We would release the update within few working days.

**Comment by ggs-victor** [comment]
We have released [1.0.40](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.40), it has an update for that.
