### ISSUE TITLE
Order status not updated

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#120]
As per the screenshot, the SSL has been issued how ever the product page within WHMCS client service does not update, or could be delayed.

See attached, showing that the cert has been issued how ever whmcs has not updated.
What cron is responsible for this if there is one?
![2020-04-12_9-49-58](https://user-images.githubusercontent.com/43058981/79063698-73a61880-7ca3-11ea-9fe2-76f961a6d71a.png)
![2020-04-12_9-50-39](https://user-images.githubusercontent.com/43058981/79063699-74d74580-7ca3-11ea-864a-93c7a81cbf17.png)

**Comment by shabsta** [comment]
I was able to force the client area to show the certificate details by clicking the 

Please advise which cron is responsible for update the certificate details?
![2020-04-12_10-19-48](https://user-images.githubusercontent.com/43058981/79064306-182a5980-7ca8-11ea-8a21-72ce661d3572.png)
![2020-04-12_10-22-38](https://user-images.githubusercontent.com/43058981/79064308-195b8680-7ca8-11ea-97ae-cdcbd2b9841e.png)

**Comment by vlad-evg** [comment]
On the screenshots you can see that the certificate in WHMCS has the status `Active` so it looks like everything is fine.

This cron is responsible for updating status certificates

0 /1    php -q /home/dev24/public_html/dev/modules/addons/SSLCENTERWHMCS/cron/cron.php

This cron is responsible for updating details about certificates

0 0   * php -q /home/dev24/public_html/dev/modules/addons/SSLCENTERWHMCS/cron/certificateDetailsUpdater.php
