### ISSUE TITLE
Display Date in Client Date format

### ISSUE THREAD

**Issue by bady1985** [gogetssl/whmcs-addon#121]
Currently the Valid from and valid till date is displayed in the customer area in the format YYYY-MM-DD, it would be nice if this could be displayed in the date format of the customer.

WHMCS already provides a function to convert the date for this, you just have to replace 2 lines in /modules/servers/SSLCENTERWHMCS/controllers/server/clientarea/home.php:

replace line 148:
`$vars['validFrom'] = $certificateDetails['valid_from'];` 
with 
`$vars['validFrom'] = fromMySQLDate($certificateDetails['valid_from'], false, true);` 

and line 150:
`$vars['validTill'] = $certificateDetails['valid_till']; `
with
`$vars['validTill'] = fromMySQLDate($certificateDetails['valid_till'],false,true);`

**Comment by vlad-evg** [comment]
Feature released now in [v.2.4.4. release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.4)
