### ISSUE TITLE
Unable to configure certs for IP address

### ISSUE THREAD

**Issue by certpr** [gogetssl/whmcs-addon#123]
Description:
The current version (v2.4.3) doesn't allow users to configure the Sectigo Instant SSL Premium and GoGetSSL PublicIP SAN for IP addresses:

For **GoGetSSL PublicIP SAN** it doesn't accept the No Common Name CSR  - although it's mandatory for this SSL - and the IP address mentioned in the SAN list field, displaying this error - https://prnt.sc/s8il63

For **Sectigo InstantSSL Premium** - After configuring the SSL with an IP address CSR and selecting the HTTP method - https://prnt.sc/s8in6y - after clicking continue, it displays the following error - 
"The following errors occurred: You must choose an approver email address" 
https://prnt.sc/s8inen

Please kindly fix these bugs to allows users to configure these SSLs for IP addresses.

**Comment by vlad-evg** [comment]
Yes, that are known issues. We expect to release fix within 5-7 days.

**Comment by qya** [comment]
So this problem already solved or still on development ?

**Comment by vlad-evg** [comment]
Feature released now in [v.2.4.4. release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.4)
