### ISSUE TITLE
Wrong Next Due Date on Renewal

### ISSUE THREAD

**Issue by certpr** [gogetssl/whmcs-addon#124]
**Renewal Settings** - https://prnt.sc/s8j4a5 - when the user clicks on Renew, a Renewal invoice is created. Once paid, a New Order with the renewed domain name is created, which shall be configured manually. 

**Issue:** When the user configures and issues the renewed SSL Certificate, the following happens:

1. **Next Due Date** for the original (expiring) SSL Certificate - becomes +1, 2, or 3 yrs, depending on the Billing Cycle of the Renewed SSL - e.g. this expired SSL got a +1 yr - https://prnt.sc/s8jdid

2. **Next Due Date** for the renewed (new) SSL Certificate sometimes (not all the time) becomes +1 yr, too, for an unknown reason. 

Because of the above Next Due Date bug, the users get confused about the expiry date of their SSLs. 

Please kindly fix this bug.

**Comment by certpr** [comment]
Any updates on this issue?

**Comment by vlad-evg** [comment]
Yes, that is done. We are preparing release in next 1-3 days

**Comment by certpr** [comment]
Awesome, thanks!

**Comment by certpr** [comment]
Is this issue fixed in v.2.4.4. release, too?

**Comment by vlad-evg** [comment]
The value of the `Next due date` field is set to the same as the expire date of the certificate.
