### ISSUE TITLE
Possible for clients to get free SANs

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#125]
This is not really a bug report per se - it's just how WHMCS works.
Let's say a client orders a certificate and orders 3 additional SANs. The client can immediately after ordering go and downgrade to 0 additional SANs and have the amount for the SANs credited, even though their certificate is created with 3 additional SANs.

Would this be possible to fix?

**Comment by vlad-evg** [comment]
so technically we are speaking about disabling downgrade option?

**Comment by DennisSkov** [comment]
Well.. Possibly - unless there's a way to disable WHMCS giving the client a credit for those specific downgrades.

**Comment by vlad-evg** [comment]
You can disable adding credits during the downgrade https://docs.whmcs.com/Credit_Tab#Credit_on_Downgrade

Additional modifications will be required to block the downgrade completely, but this is not a module issue, it's just how WHMCS works.
