### ISSUE TITLE
Can't Reissue Wildcard SSLs

### ISSUE THREAD

**Issue by certpr** [gogetssl/whmcs-addon#127]
WHMCS GoGetSSL - Latest version v2.4.4:

When attempting to Reissue any Wildcard SSL, users receive an Incorrect CSR message - https://prnt.sc/sx7xsx - although their CSRs have no issues and the common name is in wildcard format, as required. 

When these SSLs are reissued manually in the GoGetSSL dashboard, no error is displayed and the reissue is successful. 

The Incorrect CSR message - https://prnt.sc/sx7xsx - is displayed only in WHMCS GoGetSSL - Latest version v2.4.4.

Please fix this bug asap.

**Comment by vlad-evg** [comment]
Issue solved. Sorry, took longer :/

Check [the latest](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.5) release.
