### ISSUE TITLE
Renewal Email Notification

### ISSUE THREAD

**Issue by cenourinha** [gogetssl/whmcs-addon#129]
---
name: Renewal Email Notification
about: Send an e-mail to customer when a SSL renewal invoice is paid

---

When a customer pays a SSL Certificate renewal invoice, he isn't notified of any additional procedure they need to follow (validate the certificate, install new certificate in server, etc).

It would be great to have an option to send a template email when a customer pays the renewal invoice, to make sure they validate the domain and install the new ssl certificate in their webserver (cPanel, Plesk, IIS, other).

**Comment by vlad-evg** [comment]
Great idea. We would discuss that with developers now

**Comment by vlad-evg** [comment]
That will be implemented till ~26th June

**Comment by hendranata** [comment]
helo
do u provide stable version? which one is stable..which one is under develop..so on..

**Comment by vlad-evg** [comment]
Yes, the latest one is a stable version with all the latest fixes. For the past 60 days, there was no critical issues reported.

**Comment by vlad-evg** [comment]
Feature released: 
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.6

**Comment by cenourinha** [comment]
When is this sent (on invoice paid or a cron job)? It seems this email was never sent in our installation.
