### ISSUE TITLE
Auto Calculate Pricing 

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#13]
**Is your feature request related to a problem? Please describe.**
Yes, example: 
1. When SSL's are renewed, it is renewed for last price, not current price.
2. SSL reseller price in GGSSL backend can change often, sometimes leading to a total loss of revenue if the reseller price (our price) is more than what we are selling the SSL for.

**Describe the solution you'd like**
Auto Calculate the price based on a percentage markup/profit that we choose.
Example: 
GGSSL reseller price (our price) is $1 , our markup is 20% , so WHMCS should set price at $1.20.  
This should run on a cron each night. Also, the ability to override or set the percentage per customer. 

**Describe alternatives you've considered**
All of our WHMCS modules for reselling anything from domain names to servers allow you to set the markup/profit percentage and the prices in WHMCS are calculated from that. 

**Additional context**
Please also include all other GGSSL products, SSL, SANS, Security Products.

I think this would be a very popular feature :)

**Comment by charliehu** [comment]
Hi,

We using custom script for this purpose: https://gitrepo.hu/snippets/1

**Comment by ggs-victor** [comment]
Auto calculation is under production now, we expect to receive that function within 20-30 days. That task is quite large as includes CRON jobs, API, currency conversions.

**Comment by ggs-victor** [comment]
New feature added, please check [new release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.0), make sure to perform MIGRATION from v.1.0.42 to v.2.0.0
