### ISSUE TITLE
Oops! Error on new customer order

### ISSUE THREAD

**Issue by jvkranenburg** [gogetssl/whmcs-addon#131]
Customer ordered a domain transfer. For .nl domains this is free of charge. So an 0.00 invoice is created and therefor directly marked as paid.

Customer gets the attached screenshot as an error:

![SSLCenterWHMCS issue](https://user-images.githubusercontent.com/7745377/87548605-07292400-c6ad-11ea-9965-563b4736b9ff.png)

Did we install something incorrectly or is this an issue in de InvoicePaid hook at the GoGetSSL extension?

Module version: 2.4.6
WHMCS version: 7.10.2

**Comment by vlad-evg** [comment]
Let us check ASAP

**Comment by vlad-evg** [comment]
Please provide WHMCS admin access via ticket so developers can investigate

**Comment by jvkranenburg** [comment]
Done! Ticket #ORV-485-39515

**Comment by vlad-evg** [comment]
Sorry for the delay, please try that release, it should fix that issue
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.7a

**Comment by jvkranenburg** [comment]
NP, installed v2.4.7a.
Tnx for the quick response!
