### ISSUE TITLE
GoGetSSL Wildcard Multi-Domain configuration issue

### ISSUE THREAD

**Issue by certpr** [gogetssl/whmcs-addon#135]
Currently, it's impossible to configure the  GoGetSSL Wildcard Multi-Domain SSL for any wildcard SAN - https://prnt.sc/tmf5gl - it allows only non-wildcard SANs. 

Tested on the latest v. 2.4.7

Please fix this bug in order to allow customers to configure this product for wildcard SANs as well, as advertised. 

Thank you!

**Comment by vlad-evg** [comment]
Please try that
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.7b

**Comment by certpr** [comment]
Is the issue fixed in this version - v2.4.7b?

**Comment by vlad-evg** [comment]
Yes, it is special fix for that issue

**Comment by certpr** [comment]
Got it, thank you for the quick fix!

**Comment by certpr** [comment]
Hi, 

This bug reappeared in version v2.5.9 - https://drive.google.com/file/d/1DB3lkrK9cpEw4cmUrcqV0e7QyqP-VyvC/view?usp=sharing

Your product GoGetSSL Wildcard Multi-Domain SSL doesn't allow users to configure it for wildcard SANs.

Please fix it.

Thank you!

**Comment by vlad-evg** [comment]
Thank you, we routed that to developers now

**Comment by vlad-evg** [comment]
Developers were not able to reproduce the issue and require a complete access to WHMCS. Please provide it within the Ticket

**Comment by certpr** [comment]
The error appears ONLY after you select the domain validation method. 

Did the developers complete this stage as well when testing?

**Comment by vlad-evg** [comment]
I guess you are generating CSR for *. wildcard domain, and that is wrong. CSR should be for Single domain only and Wildcard SAN items should be added to SAN fields like: *.domain.com

**Comment by certpr** [comment]
No, the CSR wasn't generated for a wildcard domain name - https://drive.google.com/file/d/1KdR_IBbuKXZtFDvQpQJeB5N1nkx4TT4Y/view?usp=sharing

As mentioned above, the error appears ONLY after you select the domain validation method.

Did the developers complete this stage as well when testing?

**Comment by vlad-evg** [comment]
Yes, we did a complete test using our environment + Modules Garden did the same test.

During the test we used GoGetSSL™ Multi-Domain Wildcard SSL

**Comment by certpr** [comment]
Hi Vlad, 

Thank you for looking into it with Modules Garden. 

We checked once again and we were able to reproduce the error only on a certain local device. 
On other devices, the error wasn't present. 

For this reason, we can consider this issue closed. Thank you for your help.
