### ISSUE TITLE
Modals and WHMCS 7.10.2

### ISSUE THREAD

**Issue by PersianWeb** [gogetssl/whmcs-addon#138]
Hello there,
The Modal boxes is not working in WHMCS 7.10.2.
e.g. for RSA Private Key.
Regards.

**Comment by vlad-evg** [comment]
Hello,

can you provide any screenshots? As well as your WHMCS SSL addon version?

**Comment by PersianWeb** [comment]
SSLCENTER 2.4.8
Here you go:
this forms apear "**Below Footer**":
![screenshot](https://user-images.githubusercontent.com/30745668/89124808-0be43980-d4ef-11ea-99f3-f16838c4744b.jpg)
also console is clear.

**Comment by vlad-evg** [comment]
I see no styling (CSS), that could affect showing modal boxes. What is the URL of your system so we can try test it

**Comment by PersianWeb** [comment]
i've notice that in chrome devTools -> Source there is no css related to ssl center loaded:
![screenshot](https://user-images.githubusercontent.com/30745668/89125148-8d3ccb80-d4f1-11ea-9f10-1397adddaf7c.jpg)
how can i send login info to you?

**Comment by vlad-evg** [comment]
That is default modal box by WHMCS and template "SIX", the location of CSS for modal box will be here
[your_server]/templates/six/css/all.min.css

**Comment by PersianWeb** [comment]
I've Changed and reset everything to whmcs defaults with default theme "Six".
There is no "#getprivatekey" button even with whmcs default six theme.
