### ISSUE TITLE
Remove automatic Credit when downgrading an Active product

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#14]
**Describe the bug**
After activating the Upgrade/Downgrade option for adding/changing SANs, we found the following issue:

When a user upgrades the product (adds more SANs), activates the product (the SSL Certificate gets issued) and then chooses to downgrade (remove the added SANs), the system automatically credits the account with the removed SANs price. 

**Video**
https://screencast.com/t/F1rYIMSrAwt

**Expected behavior**
This feature should be removed, because, for example, users might choose to downgrade a 2-year product after 1 year of using the additional SAN, so automatically crediting the account with the 2-year SAN's price is not ok, because the user used the SAN for an entire year. 

We think this the automatic Credit feature should be in place only for a product (SSL Certificate) which has never been configured (a blank order), while for the products that have been configured and used, the automatic Credit feature should be removed.

**Comment by ggs-victor** [comment]
We have [released](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.41) new version with a fix
