### ISSUE TITLE
There is no "Get Private key" Button

### ISSUE THREAD

**Issue by PersianWeb** [gogetssl/whmcs-addon#140]
Hi
WHMCS 7.10.2
SSLCENTER WHMCS = 2.4.8
Template = Default "Six"
-
There is no Button for Get Private key:
![Annotation 2020-08-12 133651](https://user-images.githubusercontent.com/30745668/89997259-29f52b00-dca1-11ea-91d1-3841f58fab80.jpg)
so users can't install issued certificates.
Kind Regards

**Comment by vlad-evg** [comment]
Hi, 

does CSR/KEY was generated on the WHMCS? The private key available only if CSR was generated using CSR generator

**Comment by PersianWeb** [comment]
Solved!
the modals didn't work with other themes rather than "Six" so i've disabled the csr generator from add-on options.
Reissued with CSR Generator and button appears.

It would be great if css file include with add-on for those who didn't use defafult six template. 
Thank you so much.
Regards
