### ISSUE TITLE
CSR validation blocks wildcard SSL

### ISSUE THREAD

**Issue by NatsumeYuujinchou** [gogetssl/whmcs-addon#148]
The API decodeCSR returns below error message if the common name is a wildcard domain.
"The Common Name (Domain Name: *.futuregame.com.tw) may not contain a *. Please buy Wildcard SSL Certificate for that CSR"

In the function SSLStepTwoJS (defined in addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepTwoJS.php), once detecting an error when decoding CSR, it will throw an exception and stop rendering JS for approval emails.

**Comment by DennisSkov** [comment]
What version of the module are you using? AFAIK, that issue was fixed a long time ago.

**Comment by vlad-evg** [comment]
and what is the product you are trying to order?

**Comment by NatsumeYuujinchou** [comment]
I have the issue with the latest version 2.4.10. I was trying to order PositiveSSL Wildcard.

**Comment by vlad-evg** [comment]
can you provide CSR please?

**Comment by googlegame** [comment]
same problem, PositiveSSL Wildcard

**Comment by vlad-evg** [comment]
Can you provide CSR code? We see no issues on our side

**Comment by NatsumeYuujinchou** [comment]
Here's a CSR,

`----BEGIN CERTIFICATE REQUEST-----
MIIC6DCCAdACAQAwgaIxCzAJBgNVBAYTAkNOMRIwEAYDVQQIDAlHdWFuZ2Rvbmcx
EjAQBgNVBAcMCUd1YW5nemhvdTEdMBsGA1UECgwUaHVhcm9uZ3poZW5ncXVhbi5j
b20xCzAJBgNVBAsMAklUMR8wHQYDVQQDDBYqLmh1YXJvbmd6aGVuZ3F1YW4uY29t
MR4wHAYJKoZIhvcNAQkBFg96enh4YTYyQGFvbC5jb20wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDC7Z4u7c1ppUAyjWESRNe4PULkF5PB69LIXdjAztWu
v8ZhFcwPxet9InYUWBoj4RHjYdtknx2xmcBcqI1vDhcorkSH2VktFo7BGvHq9Qs2
6i7N/hzluSyAteP0/jEybQb4ymXk1Wznp2fp4FZvsjrIZRoY5my/95i3YmuUOjhY
dUDBXkq+V/c9JbP0fNc4XcwZt5Brw1CDydEWe0v9gzQKJ7MyVY8CrGolY9j5J23n
bEeXC02625szxFvSihCCtgh8W3AmHca9Vt8stuBYH450CHgy5xUzKbMAwodgPoTc
jRMjzuQQOYcpVVaY3ok9ziK2qXNW3ZD9HYssiIxKt0hpAgMBAAGgADANBgkqhkiG
9w0BAQUFAAOCAQEARO6OpknWEmoJcq7XTQ6e9ZdQmn9Hr+Ituz4Ncp8LP3Nvwb94
WqC0/rZVPeaTo3xrH/qqBuZj2sPI1Mj7wwIl5VM5GOG63U6OotVspt8gLjMNgwzE
XR+NZLfpZZ/LdVb58u0gmcoklRwi3ZqPsA6RH2Bxbyq+mVzV4YjfQLLzvFg2yx6S
eLztwAmM45iOZufU/1uXEPFhkyOUdpuoRfirLlg0WOcok3gW+tMD6e/PlIHYxamk
WPxeVgINqmVaYzbC/xYgUJLxuh00Nb1crwEHiKPRvbyXVtTX1qm89b/efK8nlts6
wjW1HBOkmLXjiYW3laZgJtKZ11XO32P2uckXdw==
-----END CERTIFICATE REQUEST-----`

**Comment by vlad-evg** [comment]
Fixed now https://github.com/gogetssl/whmcs-addon/issues/148
