### ISSUE TITLE
Email address still showing

### ISSUE THREAD

**Issue by thomashoeky** [gogetssl/whmcs-addon#15]
**Describe the bug**
When the email verification is disabled in the latest version's settings the verification page still shows the email address and the title says "Certificate approval email"

**To Reproduce**
1. Order a new certificate (I have GGSSL DV)
2. Fill in the CSR etc.
3. The page with the email address will appear

**Expected behavior**
The title should say ie. "Certificate verification" and the email address part should not be on the page

**Screenshots**
![ggssl](https://user-images.githubusercontent.com/10139932/46892366-7be28500-ce6d-11e8-8fad-cb0389052bcd.JPG)

Thanks in advance!

**Comment by thomashoeky** [comment]
Also a small (other) thing: "sendCertificate" is not translatable from the actions when the certificated is ready

**Comment by ggs-victor** [comment]
We have [released](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.41) new version with a fix
