### ISSUE TITLE
Custom expiration/renewal notifications per customer

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#158]
Hi there,

We have a few customers each asking for different renewal reminders. 

One is asking for only a 90 day reminder. 
One is asking for only a 30 day reminder.

All others get one on 90, 60, 30, 15, etc. I think which is fine.

Would it be possible to add something like this? 

Perhaps the customer could set their own preference or the admin can just set it in the module like the commission rules. 

Thanks,
C

**Comment by vlad-evg** [comment]
Hey,

to be honest, we are removing 90-60 reminders, as all products now would have 30-21-14-7-3-1-0. 
90-days are not actual anymore as the max period that can be added to SSL is +30 days

**Comment by vlad-evg** [comment]
That is updated now in latest release
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.1

**Comment by qhgh** [comment]
Sorry to say our WHMCS is still sending the 90 day notice: 

22/12/2020 00:00 - Your XXX SSL expires in 90 days!

**Comment by vlad-evg** [comment]
Well, if you updated that just now. Then CRON job could take an old selection. We would check that

**Comment by qhgh** [comment]
We updated on 15th December or the 16th maybe. It's been some time and still doing it. Would you be able to help? Thanks. C.

**Comment by vlad-evg** [comment]
It is possible that the old value is still in the database. Please go to the module settings and save this value again.
