### ISSUE TITLE
last version 2.50f dose not support whmcs 8.1 new them twenty-one

### ISSUE THREAD

**Issue by googlegame** [gogetssl/whmcs-addon#159]
last version 2.50f dose not support whmcs 8.1 new them twenty-one

**Comment by vlad-evg** [comment]
can you please share issues you face?

**Comment by googlegame** [comment]
![20201210151623](https://user-images.githubusercontent.com/86212/101734199-e39ec400-3afa-11eb-8aeb-d3e7506e1550.png)

**Comment by vlad-evg** [comment]
Issue solved, please download latest release
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.1
