### ISSUE TITLE
Validation E-mail on Client Area

### ISSUE THREAD

**Issue by cenourinha** [gogetssl/whmcs-addon#161]
After the customer configures, submit the CSR & select the validation mail in order to get the Certificate Issued, he is not able to check again what validation e-mail he selected in the Certificate page and the only way for us to check that information is to check on GoGetSSL control panel or in the tblsslorders table of the database.

Please make the necessary changes to show the e-mail to the customer when the Certificate is pending validation (and after that too).

**Comment by vlad-evg** [comment]
What is the SSL addon version?

**Comment by cenourinha** [comment]
Last version (2.5.1)

**Comment by cenourinha** [comment]
2.5.2 seems to fix it. Only misses the translation string for "Approver email".

If this information could be also included in the admin area, it would be great!

**Comment by vlad-evg** [comment]
You mean it is not possible to change that title from Translation file?

**Comment by cenourinha** [comment]
The string is not yet in the modules/servers/SSLCENTERWHMCS/langs/english.php file.

**Comment by vlad-evg** [comment]
Should be solved now
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.3
