### ISSUE TITLE
Remove Whois Email from Validation

### ISSUE THREAD

**Issue by cenourinha** [gogetssl/whmcs-addon#162]
It would be great if you could implement an option to remove the whois contact of the domain from the validation email list. Sometimes our own domain appears in the whois of the domain because we are one of the contacts and the customer select us as the approver (we prefer not to do the validation as we may be approving an ssl requested by someone externally by error).

Also this can make a huge mess in renewals, as the whois email can change and will not be a valid option for automated renewals.

**Comment by vlad-evg** [comment]
Thank you, we will check that option

**Comment by cenourinha** [comment]
Any update on this?

**Comment by vlad-evg** [comment]
Feature enabled
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.10
