### ISSUE TITLE
Webserver Options

### ISSUE THREAD

**Issue by cenourinha** [gogetssl/whmcs-addon#163]
When the customer is configuring the Certificate, he needs to select the webserver type. As this moment you show "IIS" and "Any Other".

Would it be possible to supress this information and always submit as "Any Other" or have the option to show to customer "cPanel", "Plesk", "Other" or maybe allow us to translate "Any Other".

**Comment by vlad-evg** [comment]
Well, historically there were around 50 options, now 2 are more than enough. As there is NO difference at all. Same certs issued and compatible with all devices. So we plan to remove the selection of software at all in JAN 2021 as deprecated functionality

**Comment by cenourinha** [comment]
I see that those options are still featured in the module. Do you have an ETA when they will be removed?

**Comment by cenourinha** [comment]
Any update on this?

**Comment by vlad-evg** [comment]
Sorry for the delay, we will ask Modules Garden to implement that fix, I will come with ETA tomorrow

**Comment by vlad-evg** [comment]
Updated and released: https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.10
