### ISSUE TITLE
"SSL Certificate - Reissue" Mail

### ISSUE THREAD

**Issue by cenourinha** [gogetssl/whmcs-addon#164]
After updating to last version of the module, i see that the "SSL Certificate - Reissue" was sent to some customers. When is this email sent?

I see it was sent to two customers who have dozen of SSL Certificates and they are unable to identify for which certificate is the notification. Also i think the notification doesnt make too sense, because it says the customer needs to reissue the certificate, but what the customer needs to do is to renew, but the invoice was not generated yet (isn't supposed to be generated 30 days before the ssl expiration)?

**Comment by vlad-evg** [comment]
Are you sure the renewal is what is needed to those orders and not reissue? The max period of SSL is 13 months so if customer using a subscription it needs to be replaced aka reissued. Please provide at least some information, like order number to check

**Comment by cenourinha** [comment]
If i'm checking the correct SSL Certificate, this is related to a certificate that will expire on 13/01/2021:
https://i.imgur.com/torbziF.png

Also, it seems the "Next Reissue" date showed in the client area is totally wrong. :S

**Comment by vlad-evg** [comment]
Yes, I see that wrong too. We will ask MG to investigate ASAP

**Comment by cenourinha** [comment]
As i'm not sure if the notification is really related to that Certificate, i added {$service_id} to the mail template in order to better track for which Certificate each notification is related to.

I recommend this to be done by default in your module or log that information in the tblmodulelogs for better tracking.

**Comment by cenourinha** [comment]
Some more examples where the Next Reissue Date is wrong:
https://i.imgur.com/ZR73YFz.png
https://i.imgur.com/9iEroev.png
https://i.imgur.com/gM6m6Q3.png
https://i.imgur.com/ODdFKaK.png
https://i.imgur.com/QvtVgRQ.png

I think that is showing incorrect in every Certificate.

**Comment by vlad-evg** [comment]
There is nothing wrong with the number of days, they are calculated properly. The days calculated as the difference between VALID FROM and EXPIRES. However, we would release an update to rename NEXT REISSUE -> NEXT RENEWAL if EXPIRES = Subscription ends to avoid misunderstanding by customers

**Comment by vlad-evg** [comment]
as for the Notification emails, we will add a new condition:

in case, if Expires = Subscription Ends the system would use RENEWAL notification email and not REISSUE. 
So Reissue email will be sent IF:
1) EXPIRES not equals subscription ends
2) ONLY for 2-3 year products

**Comment by cenourinha** [comment]
In this case it says "Reissue Certificate within 455 days" (https://imgur.com/ZR73YFz). This will make the customer think that they will need to reconfigure the SSL Certificate 455 days from now, when in reality, the SSL Certificate will need to be reissued/renewed 87 days from now.

**Comment by vlad-evg** [comment]
There is no error. The current SSL was purchased in December 2019 and is perfectly valid till March 18, 2021. All SSL issued BEFORE end of August 2020 will be still valid for the MAX period of 26 months. They will be changed to 13month SSL only in case of reissue.

**Comment by cenourinha** [comment]
This is a 1-year Certificate, so it will be valid only until the expiration date (March 18, 2021), right? The information "Reissue SSL within 455 days" will create confusion to the customer.

**Comment by vlad-evg** [comment]
Correct. Till MAR 18, 2021. Confuse, for sure. That is why I wrote above

"However, we would release an update to rename NEXT REISSUE -> NEXT RENEWAL if EXPIRES = Subscription ends to avoid misunderstanding by customers"

**Comment by vlad-evg** [comment]
Please try that release:
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.3
