### ISSUE TITLE
Can not match country name to country code

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#167]
Hi there,

Suddenly, in WHMCS v8.0.1 when we enter the CSR the module says:

**Can not match country name to country code**

Screenshot: https://snipboard.io/lD6duq.jpg 

GGSL support have checked the CSR and suggests it's a WHMCS issue. 

Can you please offer any help on this? 

Thanks,
C

**Comment by vlad-evg** [comment]
Please use that version to fix
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.4
