### ISSUE TITLE
References to GGSSL are not white label

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#17]
**Is your feature request related to a problem? Please describe.**
When enabling Orders Summary as per Wiki Instructions, references are made to "GGSSL WHMCS" on page title, the URL to the page includes GGSSLWHMCS. 

These are contradictory to "Fully White Labled solution"
A search for "GGSSL WHMCS" or "GGSSLWHMCS" reveals where the certificates are originating from.
**Describe the solution you'd like**
Remove all references to GGSSL and GGSSLWHMCS within the client area in order for the product to meet all requirements for a white label solution

**Describe alternatives you've considered**
GGSSL could be renamed to SSL and GGSSLWHMCS renamed to SSLautomation

**Comment by ggs-victor** [comment]
Dear Shabsta,

We would request to rename module to SSLCENTERWHMCS.
I will let you know once done

**Comment by ggs-victor** [comment]
There is an issue with that task. After this modification, the module will be perceived as a separate solution. it means that after uploading files to the server with the previously existing module (GOGETWHMCS), two modules will be available. The new module will have to be configured. Old SSL orders and products configured with the old module will not be automatically assigned to SSLCENTERWHMCS.

that makes a problem.

**Comment by charliehu** [comment]
Easy to modify this with an SQL query where you module servermodule in
products table.

**Comment by shabsta** [comment]
Thanks for providing feedback, are you able to provide step by step instructions in order to achieve this without breaking a live environment?

**Comment by ggs-victor** [comment]
Your request completed. please check [new release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.0), make sure to perform MIGRATION from v.1.0.42 to v.2.0.0
