### ISSUE TITLE
Due date sync for Triennially certificate

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#172]
Hello,

If customer order certificate for 3 year period, the module sync the certificate expiration date (which is one year) as due date, instead of the end of subscription date. Because of this, new invoice will be generated next year, even when clients already paid that period.

**Comment by vlad-evg** [comment]
Thank you. Routing issue to developers ASAP

**Comment by vlad-evg** [comment]
Please use that files 
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.6
