### ISSUE TITLE
GGSL offers 5 year but WHMCS module only 3

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#174]
Hi there, 

As per the WHMCS module Product Configuration: https://github.com/gogetssl/whmcs-addon/wiki/Product-Configuration it is only possible to offer 1, 2, &, 3 year SSL, but, in the GGSSL account we can buy up to 5 years.

Is this a limitation of WHMCS or can the GGSSL module be updated? 

Thanks,
C

**Comment by vlad-evg** [comment]
Hello,

unfortunately, WHMCS do not support any products for more than 3-years, nor hosting, nor domains :/
You can create 5-year product separately only :/

**Comment by qhgh** [comment]
Hi Vlad,

Thanks for clarifying.

In the past, we had many complaints from customers who only want to buy the SSL one-time (without renewal). 

As such, we had to stop offering 2 and 3 years because either the GGSL module or WHMCS would create an invoice on the next due date for them. 

Is it not possible to buy a 2 or 3 years SSL one-time (not recurring)? Is there any workaround to simply expire the SSL and not renew it automatically?
![ggsl-onetime](https://user-images.githubusercontent.com/43718405/108047575-e14a7000-703d-11eb-89c3-a046cbccb8d8.png)

Thanks,
C

**Comment by vlad-evg** [comment]
Let us think about
