### ISSUE TITLE
DCV Method drop-down is empty

### ISSUE THREAD

**Issue by yashodhank** [gogetssl/whmcs-addon#175]
**Describe the bug**
WHMCS 8.1.1 General Release8.1.1-release.1

**To Reproduce**
1. Go to 'Product Details'
2. Click on 'Awaiting Configuration - Configure Now'
3. Submit the CSR with Renewal and Any Other option from drop-down menu.
4. Click on button: Click to Continue >>
5. Certificate Verification page: DCV Method drop-down is empty.

**Expected behavior**
DCV Method drop-down options should be visible and available to select.

**Screenshots**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1083792/109082852-bd1c1c80-772a-11eb-8ba0-19f3e1ded728.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.1 (20D74)
 - Browser: Chrome, Opera, Firefox
 - Version Version 88.0.4324.192 (Official Build) (x86_64), Opera: 74.0.3911.144, Firefox:85.0.2 (64-bit),

**Comment by vlad-evg** [comment]
Hello,

what is your WHMCS SSL addon version?

**Comment by yashodhank** [comment]
Hello, sorry forgot to add, I was on 2.5.5 and today only upgraded to 2.5.6
Same issue occurred with both versions.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1083792/109116163-1bb2bc00-7766-11eb-94b9-86f28060325e.png">
Thank you

**Comment by vlad-evg** [comment]
Developers are not able to reproduce the error. Please send us WHMCS admin and FTP access via ticket

**Comment by yashodhank** [comment]
Sure, Thank you

**Comment by yashodhank** [comment]
My issue is resolved, I did deactivated module. extracted latest version downloaded files and uploaded it to right directories as mentioned in installation doc.
Configured API, clicked Migrate button couple of times and suddenly issue resolved.
Thank you

**Comment by vlad-evg** [comment]
so you were migrating from old module? Just curious what was the previous version you upgraded from :)

**Comment by yashodhank** [comment]
I was on 2.5.5
