### ISSUE TITLE
WHMCS Status 'Active' but SSL is 'Expired'

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#176]
**Describe the bug**
This is a repeat issue. Inside WHMCS the Status of the SSL service shows Active even if the SSL has expired. The CRON should/did change the Status to Completed once the SSL expired. 

**To Reproduce**
Login to WHMCS.  
Look at any expired SSL
The service is Active

**Expected behavior**
Login to WHMCS.  
Look at any expired SSL
The service should be Completed

**Screenshots**
Attached: 
![image](https://user-images.githubusercontent.com/43718405/109851153-419afd80-7c4b-11eb-8223-495d171fb02d.png)

Thanks,
C

**Comment by vlad-evg** [comment]
thank you. Passed to DEV team

**Comment by vlad-evg** [comment]
Fixed https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.7

**Comment by qhgh** [comment]
Thanks! 

I updated,  ran every CRON, but the WHMCS status does not change from Active to Completed.

**Comment by vlad-evg** [comment]
have you runned all crons?

**Comment by qhgh** [comment]
Yes, ran all of them.

**Comment by vlad-evg** [comment]
Modules Garden told that the issue is with SYNC terms. Normally it is done every 5 days. So your order was last time synced on 3rd March

You can change the synchronization date in the database
table tblsslorders -> configdata
