### ISSUE TITLE
Certificate renew not include SAN

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#18]
Hello,

We had a certificate where client ordered extra SAN-s. The module generated the renew order and the invoice correctly, however, without the extra SAN's (price also calculated based on base price without extra sans).

**Comment by ggs-victor** [comment]
Hello,

So you want renewal would have all extras previously purchased (extra SAN), correct?

**Comment by charliehu** [comment]
Yes, my client want to renew what they purchased, and extar SAN including this, because if he ordered it, they need it obviously.

**Comment by ggs-victor** [comment]
Issue fixed, please check [new release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.0), make sure to perform MIGRATION from v.1.0.42 to v.2.0.0
