### ISSUE TITLE
Can't configure new ssl

### ISSUE THREAD

**Issue by Skoroglyad** [gogetssl/whmcs-addon#180]
I use:
- whmcs x8
- gogetssl 2.5.8

I try to configure a new SSL. After step 2 I receive the error message "Validity Period is not supported. Please specify correct validity period in months for current product".
I checked the data that I sent to API. 
```
$order['period'] = 12;
```
Can you help with this issue?

**Comment by vlad-evg** [comment]
What products are you trying to order?

**Comment by Skoroglyad** [comment]
GoGet SSL Buisness Trust and RapidSSL Trial

**Comment by vlad-evg** [comment]
RapidTrial should have 1 month. Actually, all months already pre-defined by Addon:
https://www.screencast.com/t/lXOB4pxpPq

You can send us WHMCS admin access via ticket and we can investigate

**Comment by Skoroglyad** [comment]
It's interesting. I believe that period is pre-defined for the free products. 
But if I pay for the product the system takes the period from the billing period.
https://github.com/gogetssl/whmcs-addon/blob/master/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php

I'm talking about this part.
```
$order['period']     = $billingPeriods[$this->p['model']->billingcycle];//$this->p[ConfigOptions::API_PRODUCT_MONTHS]; // Required  
```
Also, I tested and bought products(RapidSSL) with different billing periods. I configured it with 1 month billing period but with another period I received the same error: "Validity Period is not supported. Please specify correct validity period in months for current product".

**Comment by vlad-evg** [comment]
Again, we will need access to check your situation. WHMCS keeps the MAX period as SSL period, so for regular RapidSSL it will be 60 months, while WHMCS would allows to sell for 12-24-36 months.

**Comment by RevZer0** [comment]
Hello, Vlad.
I agree that Trial certs are not the best example of problem we had.
Seems like problem is out of WHMCS scope. Here API logs for ordering GoGETSSL BusinessTrust EV cert.
As you can see period is valid in request.

```
Array
(
    [uri] => /orders/add_ssl_order/
    [post] => Array
        (
            [dcv_method] => email
            [product_id] => 132
            [period] => 12
            [csr] => "...."
            [server_count] => -1
            [approver_email] => admin@trustev12.com
            [webserver_type] => 18
            [admin_firstname] => ...
            [admin_lastname] => ...
            [admin_organization] => ...
            [admin_title] => sddse
            [admin_addressline1] => ...
            [admin_phone] => ...
            [admin_email] => ...
            [admin_city] => ...
            [admin_country] => SE
            [admin_postalcode] => 03040
            [admin_region] => Alabama
            [tech_firstname] => Rav
            [tech_lastname] => Zero
            [tech_organization] => ...
            [tech_addressline1] => ...
            [tech_phone] => ...
            [tech_title] => Dev
            [tech_email] => rav@kntele.com
            [tech_city] => Kiev
            [tech_country] => UA
            [tech_fax] => 234234234
            [tech_postalcode] => 03028
            [tech_region] => Kiev
            [org_name] => trustev12
            [org_division] => trustev12
            [org_lei] => trustev12
            [org_duns] => trustev12
            [org_addressline1] => trustev12
            [org_city] => trustev12
            [org_country] => AF
            [org_fax] => 324324324
            [org_phone] => 234234
            [org_postalcode] => 32423
            [org_region] => 324324
        )
)

```

And API respond with:
```
{"error":true,"message":"106","description":"Validity Period is not supported. Please specify correct validity period in months for current product"}
```
But as I understand from cert description [page  ](https://www.gogetssl.com/sslcerts/businesstrust-ev/) 12 month is valid and acceptable period.

Please advice.

**Comment by vlad-evg** [comment]
too many questions from our side, starting at what is your account ID, so maybe that product is not added to your profile. We really would appreciate if you can send us WHMCS admin access via the support ticket so we can test and check all issues

**Comment by RevZer0** [comment]
Ok,  I opened a ticket #JRS-594-94996 to proceed with this issue.
You can close this one.

Thank you, Vlad.
