### ISSUE TITLE
GoGetSSL Credentials not Working After Processing Order

### ISSUE THREAD

**Issue by dennis-it-net** [gogetssl/whmcs-addon#184]
Not sure if this should be posted here, if not, please point me to the right direction.

We created and processed an order for a client, the account credentials were posted in the order but when we tried using them in gogetssl, it did not work. What's the process?

**Comment by vlad-evg** [comment]
the best option is to create ticket from Client area and provide detailed information.

**Comment by dennis-it-net** [comment]
Thanks! Client area in modules garden or gogetssl?

**Comment by vlad-evg** [comment]
GoGetSSL :) the best option is to provide Admin Acess of WHMCS and description of the issue

**Comment by dennis-it-net** [comment]
Thank you!
