### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by jozsefhabit** [gogetssl/whmcs-addon#19]
**Describe the bug**
When we try to save Multi DOmain certificates we get this error message:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'gid' cannot be null (SQL: insert into `tblproductconfiglinks` (`gid`, `pid`) values (, 86))

The 'pid' value is always correct. The 'gid' value in the SQL statement is empty for some unknown reason.
We are using the latest from 1.0.x line, v1.0.42. We would like to clear this error before the migration to 2.x to prevent bigger issues later.

**To Reproduce**
1. Go to 'Products Configurator'
2. Click on 'Save' on one of the Multi Domain SAN certificates

**Comment by ggs-victor** [comment]
Can you try disable SSL addon and re-enable again? Probably proper tables were not created during module update.

**Comment by jozsefhabit** [comment]
I have been able to regenerate the API password, and fill the Configuration page of the module, and get back the product configs as well, thank you.
However, the SQL error still the same when trying to save any certificate with SAN (and configuration options).

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'gid' cannot be null (SQL: insert into `tblproductconfiglinks` (`gid`, `pid`) values (, 86))

The gid and pid values are exists in database:

> select * from tblproductconfiggroups where id = 24;
+----+--------------------------------------------+-----------------------------------------+
| id | name                                       | description                             |
+----+--------------------------------------------+-----------------------------------------+
| 24 | GoGetSSL - Comodo PositiveSSL Multi-Domain | Auto generated by module - GoGetSSL #86 |
+----+--------------------------------------------+-----------------------------------------+

> select * from tblproductconfiglinks where pid = 86;
+-----+-----+
| gid | pid |
+-----+-----+
|  24 |  86 |
+-----+-----+


> select * from tblproducts where id = 86;
+----+----------------+-----+-----------------------------------------------------------+--------------------------------------------------------------------------+--------+-------------------+--------------+--------------+-----+----------------+-------------+------------------------+---------+----------+-----------+-----------+------------+-------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+------------+------------------------+----------------+-----------------+-------------------+--------------------+----------------------+---------------------+--------------+-----------------+-------------------+-----------------+-------------------+-----------------+-----+------------------+------------------+--------------------+-------+---------+-------------+---------------------+---------------------+
| id | type           | gid | name                                                      | description                                                              | hidden | showdomainoptions | welcomeemail | stockcontrol | qty | proratabilling | proratadate | proratachargenextmonth | paytype | allowqty | subdomain | autosetup | servertype | servergroup | configoption1 | configoption2 | configoption3 | configoption4 | configoption5 | configoption6 | configoption7 | configoption8 | configoption9 | configoption10 | configoption11 | configoption12 | configoption13 | configoption14 | configoption15 | configoption16 | configoption17 | configoption18 | configoption19 | configoption20 | configoption21 | configoption22 | configoption23 | configoption24 | freedomain | freedomainpaymentterms | freedomaintlds | recurringcycles | autoterminatedays | autoterminateemail | configoptionsupgrade | billingcycleupgrade | upgradeemail | overagesenabled | overagesdisklimit | overagesbwlimit | overagesdiskprice | overagesbwprice | tax | affiliateonetime | affiliatepaytype | affiliatepayamount | order | retired | is_featured | created_at          | updated_at          |
+----+----------------+-----+-----------------------------------------------------------+--------------------------------------------------------------------------+--------+-------------------+--------------+--------------+-----+----------------+-------------+------------------------+---------+----------+-----------+-----------+------------+-------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+------------+------------------------+----------------+-----------------+-------------------+--------------------+----------------------+---------------------+--------------+-----------------+-------------------+-----------------+-------------------+-----------------+-----+------------------+------------------+--------------------+-------+---------+-------------+---------------------+---------------------+
| 86 | hostingaccount |   3 | Comodo PositiveSSL Multi-Domain (3 domain included)  |        |      0 |                 1 |            0 |            0 |   0 |              0 |           0 |                      0 | onetime |        0 |           | payment   | GGSSLWHMCS |           0 | 77            | 24            | on            | 2             |               |               |               |               |               |                |                |                |                |                |                |                |                |                |                |                |                |                |                |                |            |                        |                |               0 |                 0 |                  0 |                    1 |                     |            0 |                 |                 0 |               0 |            0.0000 |          0.0000 |   1 |                0 |                  |               0.00 |     0 |       0 |           0 | 0000-00-00 00:00:00 | 2018-08-31 18:58:24 |
+----+----------------+-----+-----------------------------------------------------------+--------------------------------------------------------------------------+--------+-------------------+--------------+--------------+-----+----------------+-------------+------------------------+---------+----------+-----------+-----------+------------+-------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+------------+------------------------+----------------+-----------------+-------------------+--------------------+----------------------+---------------------+--------------+-----------------+-------------------+-----------------+-------------------+-----------------+-----+------------------+------------------+--------------------+-------+---------+-------------+---------------------+---------------------+

**Comment by ggs-victor** [comment]
we would check that ASAP

**Comment by jozsefhabit** [comment]
Thank you. Addition information, that we have experienced the same issue with 1.0.41 version as well, maybe with older versions too, didn't had to change product configs too frequently.

**Comment by jozsefhabit** [comment]
Any update on this, please?

**Comment by ggs-victor** [comment]
Issue fixed with [v.2.0.1 release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.1)
