### ISSUE TITLE
Plugin need /vendor/whmcs/whmcs-foundation/lib/Log/Loader.php in Capnel

### ISSUE THREAD

**Issue by ystartgo** [gogetssl/whmcs-addon#191]
When I enable this plugin in WHMCS Cpanel
show some error
Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/XXXXX/public_html/XXXX/vendor/whmcs/whmcs-foundation/lib/Log/Loader.php' (include_path='.:/opt/alt/php7X/usr/share/pear') in /home/XXXXX/public_html/XXXX/vendor/whmcs/whmcs-foundation/lib/Log/ErrorLog.php:15
Stack trace:
#0 /home/XXXXX/public_html/XXXX/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/XXXXX/...', 15)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

until I create a blank Loader.php file at /vendor/whmcs/whmcs-foundation/lib/Log/
can fix this issue

**Comment by vlad-evg** [comment]
Very strange. Will be great if you can provide FTP access within Support Ticket and developers would dig all issues
