### ISSUE TITLE
servers module incompatible with latest whmcs

### ISSUE THREAD

**Issue by vanwho** [gogetssl/whmcs-addon#193]
**Describe the bug**
Since update to WHMCS v8.2.x the customer area fails to load with generic error has occurred failure, with modules/servers/SSLCENTERWHMCS being the culprit.

**To Reproduce**
1. WHMCS at version 8.2.1, whmcs-addon at latest commit or release v2.6.0
2. modules/addons/SSLCENTERWHMCS and modules/servers/SSLCENTERWHMCS loaded in whmcs directories
3. WHMCS Client area will not load and displays generic Oops error message, no detailed stacktrace.
4. remove/unlink modules/servers/SSLCENTERWHMCS directory and WHMCS client area will load again

**Expected behavior**
WHMCS Client area loads

All browsers.
System: Ubuntu, Apache and php-fcgi

**Comment by vanwho** [comment]
Just uncommented lines 12-14 here: https://github.com/gogetssl/whmcs-addon/blob/master/modules/servers/SSLCENTERWHMCS/hooks.php#L11-L14

And it works, now.

**Comment by hotzy** [comment]
Thank you, we will review that carefully and respond

**Comment by vlad-evg** [comment]
Thank you, the issue fixed
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.6.1
