### ISSUE TITLE
No "Renew" button in client area

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#199]
The "Renew" button is no longer visible in the client area. Unfortunately, I have no idea when it stopped showing.
We're on the latest version of the module.

"Visible "Renew" button in Client Area" is enabled and "Create automatical renewal invoice" is disabled for both One Time and Recurring orders.

As far as I understand, it should show when there's 90 days left of the certificate. In one case, the certificate expires on February 10th 2022, but there's no renew button.

**Comment by vlad-evg** [comment]
It should show before 30-days. Can you please submit support ticket with us and provide admin access + order number to investigate?

**Comment by DennisSkov** [comment]
I've created a ticket. Thanks!
