### ISSUE TITLE
SAN configurations function cannot be fully unchecked

### ISSUE THREAD

**Issue by CodeCodeMore** [gogetssl/whmcs-addon#2]
The new module for the SSL may have bugs in it. Any SAN once checked to enable the SAN configurations function, cannot be fully unchecked, as the SAN configurations are still active in the front-end after being unchecked.

If the SAN is unchecked again, SAN function is shown as disabled in the back-end as well as the database, but it's still active in the front-end for configurations.

Anyone who wish to reproduce the problem, remember to create a new product for the testing.

Any fixes post here will be much appreciated.

**Comment by ggs-victor** [comment]
Thank you. We just reported that to the Developers and awaiting new release with the fix.

**Comment by ggs-victor** [comment]
The issue has been fixed with **1.0.31** release

**Comment by CodeCodeMore** [comment]
Can you please tell me where is the version of 1.0.31located? 

So far the version I have re-downloaded today is 1.0.14 and it's what the problem have reported above(The "Download addon files" button says: Version 1.23, 2018.05.11, and the downloaded folder says v1.24, inside the file is 1.0.14),  so I can't found it have any changes unfortunately.

**Comment by ggs-victor** [comment]
You can download it here: https://github.com/gogetssl/whmcs-addon/releases
