### ISSUE TITLE
Existing certificate doesn't match with the Renewed (expiry notifications)

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#20]
When a client renews his SSL Certificate (pays the renewal invoice, configures, validates, issues and installs the renewed SSL Certificate), he keeps getting the expiry notifications (send 90, 30, 15, 10, 5, 3, 1 and 0 days before expiry) although he already uses the renewed SSL Certificate. 

How to match the existing certificate with the renewed one so that the client stops getting expiry notifications since he already uses the renewed certificate?

**Comment by ggs-victor** [comment]
Thank you very much for describing the issue. I believe we need build special functionality to stop renewal messages if new renewal orders placed. We would check how to do that ASAP

**Comment by ggs-victor** [comment]
Issue fixed with [v.2.0.1 release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.1)
