### ISSUE TITLE
Auto-renew invoices being generated when function disabled

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#201]
Hi there,

We have the issue again where invoices are being generated for SSL renewal, but we do not want auto-renew and that renewal feature is disabled. 

Also, the invoice does not say what SSL it is for, so us nor the customer can renew it even if we wanted to.

Please can you help us with this?

Thanks,
C

**Comment by DennisSkov** [comment]
Did you manage to fix this? We're having the same issue.

**Comment by vlad-evg** [comment]
Yes, that is fixed. We expect to release new module within next couple of days

**Comment by vlad-evg** [comment]
Issue fixed within the latest 2.7.0 module
