### ISSUE TITLE
Support for code signing certificates

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#208]
Would it be possible to add support for code signing certificates?
As it is now, it's very difficult to manage these types of certificates in WHMCS as the certificate will always have the status "Awaiting configuration".

If a code signing certificate expires, how would it be renewed in WHMCS as it is now?

**Comment by DennisSkov** [comment]
Any feedback on this?

**Comment by vlad-evg** [comment]
Dear Denis,

Yes, CodeSigning certs are on our roadmap, we plan to integrate them into API within October 2022 and once done it will be done for WHMCS too

**Comment by DennisSkov** [comment]
Hi @vlad-evg 

Is there any update on this?

**Comment by vlad-evg** [comment]
We will add it Q1 2024.
