### ISSUE TITLE
3 Improvements to new module

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#21]
**Is your feature request related to a problem? Please describe.**
On the SSLCENTER WHMCS page, clicking on the product opens in to a new tab / window

**Describe the solution you'd like**
Clicking on the certificate should open in the same window and not a new window

**Is your feature request related to a problem? Please describe.**
On the Certificate Approver Email Page, select http validation click Next to continue
Now on the Configuration Complete page, the link (button) below "Your SSL certificate configuration has now been completed and sent to the Certificate Authority for validation. You should receive an email from them shortly to approve it." take you back to WHMCS client page, where as clicking the blue button Back to Service Details takes you back to service configuration where you can get the http validation details.

**Describe the solution you'd like**
Replace the Back to client area button with  Back to Service Details button

**Additional context**

**Is your feature request related to a problem? Please describe.**
Manage Product page for certificates uses fa fa-archive fa-stack-1x fa-inverse as the icon

**Describe the solution you'd like**
Use SSL related icon such as
https://fontawesome.com/icons?d=gallery&q=ssl
or
https://fontawesome.com/icons/shield-check?style=solid

**Comment by ggs-victor** [comment]
We would review that shortly

**Comment by ggs-victor** [comment]
Issue fixed with [v.2.0.1 release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.1)
