### ISSUE TITLE
Can't validate with DNS on order

### ISSUE THREAD

**Issue by IIPoliII** [gogetssl/whmcs-addon#215]
I have an issue when I order an SSL certificate directly with DNS validation.

Here is how to reproduce it.
1. Create a product with the 90 days trial certificate
2. Place an order
3. Press configure now in the client area
4. Generate the CSR and continue
5. Choose DNS directly here as validation method
6. Press next and get the error 

`
Error: Class 'MGModule\DNSManager2\loader' not found in /var/www/html/manager/includes/api/dnsmanager.php:18
Stack trace:
#0 /var/www/html/manager/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): unknown()
#1 /var/www/html/manager/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): WHMCS\Api\V1\Api->executeApiCall()
#2 /var/www/html/manager/includes/functions.php(0): WHMCS\Api\V1\Api->call()
#3 /var/www/html/manager/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(355): localAPI()
#4 /var/www/html/manager/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(66): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->orderCertificate()
#5 /var/www/html/manager/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(46): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->SSLStepThree()
#6 /var/www/html/manager/modules/servers/SSLCENTERWHMCS/SSLCENTERWHMCS.php(68): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->run()
#7 /var/www/html/manager/configuressl.php(0): SSLCENTERWHMCS_SSLStepThree()
#8 {main}`

It looks like something is wrong on the class : Error: Class 'MGModule\DNSManager2\loader' not found in /var/www/html/manager/includes/api/dnsmanager.php:18 and it can't be found.

If you however do DNS validation afterwards (continue with email validation and switch later on to dns) it works correctly.

**Comment by vlad-evg** [comment]
Hello,

what is your current SSL addon version?

**Comment by IIPoliII** [comment]
> Hello,
> 
> what is your current SSL addon version?

Hello,
Thanks for your reply I have the latest : v2.7.7a

**Comment by IIPoliII** [comment]
> Yes, looks the issue is on DNS manager from ModulesGarden, we just notified them, and they will check it. However, for sure not quicker than Monday (

I see, so even if I haven't the module installed from them.
It is used in the code right?

**Comment by vlad-evg** [comment]
ModulesGardens were not able to reproduce the error. They will need WHMCS admin access and FTP, please send it to us via Ticket
