### ISSUE TITLE
Error when configuring a certificate using your latest addon version

### ISSUE THREAD

**Issue by munteanu210** [gogetssl/whmcs-addon#216]
Dear support,

We installed the latest version ([v2.7.7a](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.7.7a)) of your WHMCS addon. We had 4 incidents where customers wrote us that they cannot configure their SSL Certificate. Some customers tried to configure Wildcard certificates (*.example.com) and one tried to configure a single domain (example.com) certificate.

They all got the following error message: "An error occured"
See [screenshot 1](https://drive.google.com/file/d/1vQ5d2G0xO-9Dh2SuFGzpQY6td_1MqBf0/view?usp=drivesdk) and [screenshot 2.](https://drive.google.com/file/d/1aTXnJ7o0HHU7iKxbkGIZlmHUMOBGhwaE/view?usp=drivesdk).

Could you please help troubleshoot and resolve this problem?

**Comment by vlad-evg** [comment]
Dear Roman,

Can you please provide WHMCS admin access via ticket to check the logs quickly?
