### ISSUE TITLE
Renewal Invoices - changed from Overdue if unpaid to something like Upcoming/Pending payment

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#22]
**Is your feature request related to a problem? Please describe.**
One of our customers was highly frustrated by the fact that the automatic Renewal Invoice gets an Overdue status (becomes a debt) and stars a series of Overdue emails, if he doesn't pay it. He claimed it to be "shady".

**Describe the solution you'd like**/**Describe alternatives you've considered**
Is it possible to change the status, type and/or structure of this automatic Renewal Invoice, so that:

1. It doesn't become overdue during the 90 days period beginning with the date it was generated until the corresponding SSL Certificate expires (therefore, the overdue emails aren't generated by the system)
2. It displays instead an "Upcoming/Pending" Payment message (that doesn't seem "shady" and doesn't freak out the client)
3. If the client didn't pay the invoice after the SSL Certificate expires, the invoice becomes canceled (since he can't use the Renew button and feature anymore once the SSL Certificate expired).

**Comment by ggs-victor** [comment]
Thank you, we would implement update

**Comment by sergiurosca** [comment]
We have numerous customers that become frustrated by this issue. Many are corporate customers who would buy again, but we risk losing them because of these frictions that should not exist. Also, it’s causing a lot of support tickets which consume time. Could you please take care of this issue? We submitted it more than a month ago, and it’s been neglected for too long.

**Comment by vlad-evg** [comment]
The [latest release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.4) has the fix for that. You will need to use [Wiki Guide](https://github.com/gogetssl/whmcs-addon/wiki/Additional-Integration#renewal-invoices)

**Comment by sergiurosca** [comment]
After upgrading to the new version, the renewal invoices received a "Pending Payment" status, but no active "Pay Now" button: https://screencast.com/t/wzErxdPOy

How to make the button display on the invoices?
