### ISSUE TITLE
Cannot retrieve private key after the certificate is issued / reissued.

### ISSUE THREAD

**Issue by MnM202** [gogetssl/whmcs-addon#220]
**Describe the bug**
The Get private key button is gone after the certificate is issued.
**To Reproduce**
1. Create a certificate by using the CSR generator.
2. Wait until the certificate is issued.
3. The get private key button is gone.

**Expected behavior**
We expect to be able to obtain the private key at all times if the private was generated in WHMCS.

**Screenshots**
![Screenshot 2022-11-07 at 22 52 59](https://user-images.githubusercontent.com/113260396/200423868-58122a9a-e7f1-4a10-8fe6-0fea06764d50.png)

**Desktop (please complete the following information):**
 - WHMCS 8.5 / GoGetSSL latest

**Comment by vlad-evg** [comment]
We will check it shortly

**Comment by vlad-evg** [comment]
Developeres requires access to your environment, as we are not able to reproduce the error. Please provide it within the ticket
