### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by gossdhosting** [gogetssl/whmcs-addon#221]
**Describe the bug**
The plugin is not compatible with PHP 8.1. WHMCS's Latest version 8.6 added support to PHP 8.1. This plugin breaks the WHMCS when upgraded to PHP 8.1 by giving the following error-

Error: Attempt to modify property "connection" on null in /home/xxxx/public_html/billing/modules/addons/SSLCENTERWHMCS/mgLibs/MySQL/Query.php:71
Stack trace:
#0 /home/xxxx/public_html/billing/modules/addons/SSLCENTERWHMCS/mgLibs/process/AbstractMainDriver.php(103): MGModule\SSLCENTERWHMCS\mgLibs\MySQL\Query::useCurrentConnection()
#1 /home/xxx/public_html/billing/modules/addons/SSLCENTERWHMCS/hooks.php(351): MGModule\SSLCENTERWHMCS\mgLibs\process\AbstractMainDriver::I()
#2 [internal function]: SSLCENTER_displaySSLSummaryInSidebar()

**Comment by vlad-evg** [comment]
The current module does not support PHP 8.1 yet. Developers already working on it, we should publish compatible one within next 3-5 working days

**Comment by vlad-evg** [comment]
Version v.2.8.0 compatible with PHP8

https://github.com/gogetssl/whmcs-addon/releases/tag/v2.8.0
