### ISSUE TITLE
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 

### ISSUE THREAD

**Issue by tauseefpk** [gogetssl/whmcs-addon#223]
Error:
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.
 
If the problem persists, please contact us.
 
« Back to Homepage
 
For additional assistance, please reference the WHMCS TroubleShooting Guide »
 
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tblhosting.packageid `` inner join `tblsslorders` on `tblsslorders`.`serviceid` ' at line 1 in /home/webhostn/public_html/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(333): PDO->prepare('select `tblhost...')
#1 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `tblhost...', Array)
#2 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('select `tblhost...', Array, Object(Closure))
#3 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(342): Illuminate\Database\Connection->run('select `tblhost...', Array, Object(Closure))
#4 /home/webhostn/public_html/vendor/illuminate/database/Query/Builder.php(1583): Illuminate\Database\Connection->select('select `tblhost...', Array, true)
#5 /home/webhostn/public_html/vendor/illuminate/database/Query/Builder.php(1569): Illuminate\Database\Query\Builder->runSelect()
#6 /home/webhostn/public_html/modules/addons/SSLCENTERWHMCS/hooks.php(134): Illuminate\Database\Query\Builder->get()
#7 /home/webhostn/public_html/includes/hookfunctions.php(0): WHMCS\Utility\SafeInclude::{closure}(Array)
#8 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): run_hook('ClientAreaHeadO...', Array)
#9 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->runClientAreaOutputHook('ClientAreaHeadO...')
#10 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->outputWithoutExit()
#11 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/Http/Message/AbstractViewableResponse.php(0): WHMCS\ClientArea->getOutputContent()
#12 /home/webhostn/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php(27): WHMCS\Http\Message\AbstractViewableResponse->getBody()
#13 /home/webhostn/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(34): Zend\Diactoros\Response\SapiEmitter->injectContentLength(Object(WHMCS\ClientArea))
#14 /home/webhostn/public_html/clientarea.php(0): Zend\Diactoros\Response\SapiEmitter->emit(Object(WHMCS\ClientArea))
#15 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tblhosting.packageid `` inner join `tblsslorders` on `tblsslorders`.`serviceid` ' at line 1 (SQL: select `tblhosting`.`id` from `tblhosting` inner join `tblproducts` on `tblproducts`.`id` tblhosting.packageid `` inner join `tblsslorders` on `tblsslorders`.`serviceid` tblhosting.id `` where `tblhosting`.`userid` = 55 and `tblsslorders`.`status` = Awaiting Configuration and `tblproducts`.`servertype` = SSLCENTERWHMCS) in /home/webhostn/public_html/vendor/illuminate/database/Connection.php:713
Stack trace:
#0 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('select `tblhost...', Array, Object(Closure))
#1 /home/webhostn/public_html/vendor/illuminate/database/Connection.php(342): Illuminate\Database\Connection->run('select `tblhost...', Array, Object(Closure))
#2 /home/webhostn/public_html/vendor/illuminate/database/Query/Builder.php(1583): Illuminate\Database\Connection->select('select `tblhost...', Array, true)
#3 /home/webhostn/public_html/vendor/illuminate/database/Query/Builder.php(1569): Illuminate\Database\Query\Builder->runSelect()
#4 /home/webhostn/public_html/modules/addons/SSLCENTERWHMCS/hooks.php(134): Illuminate\Database\Query\Builder->get()
#5 /home/webhostn/public_html/includes/hookfunctions.php(0): WHMCS\Utility\SafeInclude::{closure}(Array)
#6 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): run_hook('ClientAreaHeadO...', Array)
#7 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->runClientAreaOutputHook('ClientAreaHeadO...')
#8 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->outputWithoutExit()
#9 /home/webhostn/public_html/vendor/whmcs/whmcs-foundation/lib/Http/Message/AbstractViewableResponse.php(0): WHMCS\ClientArea->getOutputContent()
#10 /home/webhostn/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php(27): WHMCS\Http\Message\AbstractViewableResponse->getBody()
#11 /home/webhostn/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(34): Zend\Diactoros\Response\SapiEmitter->injectContentLength(Object(WHMCS\ClientArea))
#12 /home/webhostn/public_html/clientarea.php(0): Zend\Diactoros\Response\SapiEmitter->emit(Object(WHMCS\ClientArea))
#13 {main}

**Comment by vlad-evg** [comment]
What is your WHMCS version and SSL addon version?

**Comment by tauseefpk** [comment]
Module Installed Version: 2.8.0
PHP Version: 7.2.34
WHMCS v7.10.1

**Comment by tauseefpk** [comment]
Module Installed Version: 2.8.0
PHP Version: 7.2.34
WHMCS v7.10.1

**Comment by vlad-evg** [comment]
Please provide us FTP access via ticket

**Comment by vlad-evg** [comment]
That would fix the issue
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.8.1
