### ISSUE TITLE
cronSendCertificate example incorrect

### ISSUE THREAD

**Issue by ITJamie** [gogetssl/whmcs-addon#227]
https://github.com/gogetssl/whmcs-addon/blob/2564881586079b048b11d4593965a241cf7b41a3/modules/addons/SSLCENTERWHMCS/langs/english.php#L33

The example displayed for cronSendCertificate is '0 3 * * *' which is 3am daily. The information text for this cron says it should be every 3 hours. 
https://github.com/gogetssl/whmcs-addon/blob/2564881586079b048b11d4593965a241cf7b41a3/modules/addons/SSLCENTERWHMCS/langs/english.php#L32

Please adjust to '0 */3 * * *' if it really is meant to be every 3 hours or otherwise change the info for this cron to say 3am. 

This language conflict exists in all 3 supplied language files

**Comment by vlad-evg** [comment]
Thank you very much. It is fixed now in the latest version [2.8.3](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.8.3)

**Comment by ITJamie** [comment]
@vlad-evg i just noticed that while the release version is named as 2.8.3 the version file in the plugin has been set to 2.8.2
