### ISSUE TITLE
Multi Wildcard Flex SSL (DV) wildcard certificates do not work ( 2.8.2 )

### ISSUE THREAD

**Issue by MnM202** [gogetssl/whmcs-addon#228]
Hi GoGetSSL,

We recently upgraded WHMCS/GoGetSSL to WHMCS 8.6.1 with GoGetSSL 2.8.2 and we noticed that Multi Wildcard Flex SSL (DV) products no longer work.

- CSR cannot be generated using *.domain.com
- If multiple SANs have been bought, no box is displayed to add the additional wildcard SANs

**Comment by vlad-evg** [comment]
Can you please provide us WHMCS admin access and FTP via Ticket?
