### ISSUE TITLE
Problem with "Price Auto Download"

### ISSUE THREAD

**Issue by jozsefhabit** [gogetssl/whmcs-addon#233]
**Describe the bug**
The Price auto Download adds the WHMCS default currency price to USD currency also, if it is not the default currency.

**To Reproduce**
1. Default currency should be something else than your currency at GogetSSL (eg.: in our case HUF is the default currency, we also have EUR and USD enabled)
2. Go to 'module Configuration
3. Set 'Rate for currency from SSLCENTER'
4. Go to 'Products Configuration'
5. Set 'Commission' to xx, enable 'Price Auto Download'
6.Update the prices with '/usr/bin/php -q /home/whmcs/public_html/docroot/modules/addons/SSLCENTERWHMCS/cron/APIPriceUpdater.php' 
7. Check the USD prices

**Expected behavior**
USD prices should be calculated same way as EUR prices

**Screenshots**
https://prnt.sc/mS3hJKwLb5KT

**Additional context**
WHMCS version: 8.6.1
SSLCENTER WHMCS addon version: 2.8.3b

**Comment by jozsefhabit** [comment]
Hi, any update on this, please?

**Comment by vlad-evg** [comment]
We will release the fix in 12 hours. Sorry for the delay

**Comment by vlad-evg** [comment]
Issue fixed:
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.8.4
