### ISSUE TITLE
Additional Integration Instructions

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#24]
**Describe the bug**
The code provided within the "Additional Integration" section, "3. Replace it with this code:" does not match the example image provided.
`{if $customProductDetailsIcon } {else} <i class="fa fa-{if $type eq "hostingaccount" || $type =="reselleraccount"}hdd-o{elseif $type eq "server"}database{else}archive{/if} fa-stack-1x fa-inverse"> {/if}`

**To Reproduce**
1. Follow the instructions provided on the page, paste the code, refresh and the page returns no content

**Expected behavior**
Custom Icons displayed as requested

**Describe the bug**
The code provided within the "Additional Integration" section, "3. And add the code on the top of the file: {if $customSSLCenterAssetsURL}

{/if} " does not match the example image provided.
`{if $customSSLCenterAssetsURL}

{/if} `
according to your example im this should be 
`{if $customSSLCenterAssetsURL}
	<link rel="stylesheet" href="{customSSLCenterAssetsURL}/css/all2.min.css">
{/if} `

**To Reproduce**
1. Follow the instructions provided on the page, paste the code, refresh and the page returns no content

**Expected behavior**
Custom Icons displayed as requested

**Comment by vlad-evg** [comment]
we would check ASAP

**Comment by vlad-evg** [comment]
The [latest release](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.4) has the fix for that. You will need to use [Wiki Guide](https://github.com/gogetssl/whmcs-addon/wiki/Additional-Integration#renewal-invoices)

**Comment by charliehu** [comment]
The "Custom Icon" section still not good.
