### ISSUE TITLE
Access to private key lost in interface after ReIssue

### ISSUE THREAD

**Issue by MnM202** [gogetssl/whmcs-addon#245]
**Describe the bug**
When we issue an SSL certificate for the first time we can download the private key.
However, after a Reissue is performed we cannot download the private key however.
I suspect this is because the Reissue form has a field that contains the CSR and that because of this the Reissue is treated as a custom CSR upload.

**To Reproduce**
1. Issue a certificate
2. Reissue the certificate

**Expected behavior**
The private key can still be downloaded after a Reissue.

**Version**
We are using the latest version of the module: v2.8.11

**Comment by vlad-evg** [comment]
Issue fixed with new release
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.8.13
