### ISSUE TITLE
Slow WHMCS clientarea.php for user with 400+ SSL

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#248]
Hi there! 

Our WHMCS is taking around 10 seconds to load the client area for a client with 400+ SSL. 

It only happens to this user.

Do you have any ideas/advice on what we can do to speed it up?

We have converted the WHMCS db to InnoDB and optimized all tables. The host server is a rather powerful VPS with 12core and 16GB RAM. MySQL tmpdir is in tmpfs (RAM) for speed.

Thanks,
C :)

**Comment by vlad-evg** [comment]
We will take a look on that ASAP

**Comment by qhgh** [comment]
> We will take a look on that ASAP

Sorry I hit enter and submitted this report before I entered the details! Hope you can see it now.
