### ISSUE TITLE
Problem Activating module

### ISSUE THREAD

**Issue by matiniamirhossein** [gogetssl/whmcs-addon#25]
Hello,
I've just installed the module and tried to activate it.
The following errors ocourred:
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `mgfw_SSLCENTER_user_commission` add constraint `mgfw_sslcenter_user_commission_client_id_foreign` foreign key (`client_id`) references `tblclients` (`id`) on delete cascade)

**Comment by vlad-evg** [comment]
Hello,

have you tried to use the module for the first time or you are upgrading from the previous version? If yes, what version you were using?

**Comment by matiniamirhossein** [comment]
Hi
We have used gogetssl module (old one)
As i know this one is a new module and its a fresh install on php 5.6 whmcs 7.6.1

**Comment by Andolini-Corleone** [comment]
Hello,

Based on your instruction (https://github.com/gogetssl/whmcs-addon/wiki/Migration-to-v.2), our member tried to upgrade from whmcs-addon-1.0.29 via 1.0.42 to SSLCENTER 2.0.0 and activated. Our WHMCS was 7.6.0 and PHP was 7.0.

Results:

(1)
WHMCS admin area -> Addons -> SSLCENTER WHMCS
->
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.mgfw_SSLCENTER_api_configuration' doesn't exist (SQL: select * from `mgfw_SSLCENTER_api_configuration` limit 1)

(2)
WHMCS admin area -> Setup -> Addon Modules -> SSLCENTER WHMCS -> Deactivate -> Are you sure you want to deactivate this module?
->
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

(3)
WHMCS -> admin area -> Setup -> Products/Services -> click edit icon of configured products
->
Oops!

Especially about (3), we never thought your module affect WHMCS itself. Your module was OK before SSLCENTER. We let our guard down and could not go back before SSLCENTER. So we lost all product cofigurations.
And we installed fresh WHMCS 7.6.1 from scratch and configured WHMCS again.

We have been waiting for the update of your SSLCENTER WHMCS module,
But we see this "Problem Activating module #25", we really are wondering if we should install SSLCENTER 2.0.3 from scratch.

Now, we just would like to know if this SSLCENTER WHMCS module is used by someone in real business on a production server or not.
If used and if you are OK, we would like to know how many resellers currently are using this SSLCENTER WHMCS module.

Please tell us the situation.

Thanks so much in advance.

**Comment by vlad-evg** [comment]
Dear Andolini-Corleone,

It is very sad to hear that you faced the problem with migration. Most of our customers already switched to that new module and do not face problems.

I would pass that issue ASAP to developers to check. Would you be able to provide WHMCS admin access and FTP if developers would require?

**Comment by Andolini-Corleone** [comment]
Dear Vladislavs Dovoreckis,

Thank you for your reply.

We found (1) and (2) last December and (3) last month. Unfortunately we already have done fresh install about latest WHMCS and can not go back to that issue version.

Now, how about running test by yourself as follows?

Fresh install Latest WHMCS
->
Fresh install Latest SSLCENTER module
->
Test Module Activate
->
Test add/modify Products/Services
->
Test Module Dectivate
->
Test again Module Activate
->
Test again Products/Services add/modify
->
Test some Real orders -> Real payment gateway(e.g. paypal/stripe Not sandbox account) and bank transfer -> Real SSLs issue
->
Test add/modify/delete order records *
->
Test again Module Dectivate
->
Test again Module Activate

* Especially, we experienced (3) issue after we just deleted some order test records. We did not other things at all.

It is FYI.

We know you have been making great efforts to develop your modules. And you know all we/resellers want is just a stable module for the real business.

We are looking forward to your reply.

Thanks so much again.

**Comment by Andolini-Corleone** [comment]
I found I forget "Test again add/modify/DELETE Products/Services". So I correct message and submit again as below.
　
　
Dear Vladislavs Dovoreckis,

Thank you for your reply.

We found (1) and (2) last December and (3) last month. Unfortunately we already have done fresh install about latest WHMCS and can not go back to that issue version.

Now, how about running test by yourself as follows?

Fresh install Latest WHMCS
->
Fresh install Latest SSLCENTER module
->
Test Activate Module
->
Test add/modify Products/Services
->
Test Dectivate Module
->
Test again Activate Module
->
Test again add/modify Products/Services
->
Test some Real orders -> Real payment gateway(e.g. paypal/stripe Not sandbox account) and bank transfer -> Real SSLs issue
->
Test add/modify/delete order records *
->
Test again add/modify/DELETE Products/Services
->
Test again Dectivate Module
->
Test again Activate Module

Especially about *, we experienced (3) issue after we just deleted some order test records. We did not other things at all.

It is FYI.

We know you have been making great efforts to develop your modules. And you know all we/resellers want is just a stable module for the real business.

We are looking forward to your reply.

Thanks so much again.

**Comment by vlad-evg** [comment]
We will do more tests now

**Comment by Andolini-Corleone** [comment]
Nice.

**Comment by vlad-evg** [comment]
Modules Gardens reported that after multiple tests they were not able to recreate the bug. It would be very helpful if you can provide access to your server/admin access to check it. Let us know if you wish to proceed with tests on your environment

**Comment by quentinnel** [comment]
Hi 

We experienced the same thing - it is very frustrating. Here are the steps taken:

Following https://github.com/gogetssl/whmcs-addon/wiki/Migration-to-v.2

1) Upgrade GGSSLWHMCS 1.0.31 to GGSSLWHMCS 1.0.42 (checked / ensured that it is upgraded)
2) Upload latest 2.0.0 version. **Have also tried this with the latest 2.1.0 version.**
3) Attempt to enable/active the SSLCENTER module. On first attempt (clicking the Activate button), it always throws the following error:

```
Addon Module Activated
SQLSTATE[HY000]: General error: 1005 Can't create table 'example_whmcs.#sql-1188_4fd' (errno: 150) (SQL: alter table `mgfw_SSLCENTER_user_commission` add constraint `mgfw_sslcenter_user_commission_client_id_foreign` foreign key (`client_id`) references `tblclients` (`id`) on delete cascade)
```

On second attempt (clicking the Activate button), it then proceeds to activate.

4) Configure access control rules for SSLCENTER
5) Disable OLD GGSSL WHMCS addon
6) Go to Addons > SSLCENTER WHMCS. Get the following error:

`Error in SQL Query:SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM mgfw_ WHERE `servertype` = ?' at line 1, Error Token:3375ff5490248ab2e059ff9038df8e78`

Can't get past this point. We have been using the old GGSSL modules for a very long time, but this new addon and migration is a complete show stopper.

Here is the debug info:

---

Date: 07/06/2019 16:16 - Module: mgerror - Action: mgmodule\sslcenterwhmcs\models\whmcs\errors

Request

```
Array
(
    [message] => Error in SQL Query:SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM mgfw_ WHERE `servertype` = ?' at line 1
    [code] => 1
    [token] => a919dc5effe726dc5d9b4a6fee66c24c
)
```

Response

```
MGModule\SSLCENTERWHMCS\mgLibs\MySQL\Exception Object
(
    [_query:MGModule\SSLCENTERWHMCS\mgLibs\MySQL\Exception:private] => SELECT  FROM mgfw_ WHERE `servertype` = 'GGSSLWHMCS'
    [_token:MGModule\SSLCENTERWHMCS\mgLibs\exceptions\Base:private] => a919dc5effe726dc5d9b4a6fee66c24c
    [message:protected] => Error in SQL Query:SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM mgfw_ WHERE `servertype` = ?' at line 1
    [string:Exception:private] => 
    [code:protected] => 1
    [file:protected] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/mgLibs/MySQL/Query.php
    [line:protected] => 166
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/mgLibs/MySQL/Query.php
                    [line] => 514
                    [function] => query
                    [class] => MGModule\SSLCENTERWHMCS\mgLibs\MySQL\Query
                    [type] => ::
                    [args] => Array
                        (
                            [0] => SELECT  FROM mgfw_ WHERE `servertype` = :cond0
                            [1] => Array
                                (
                                    [:cond0] => GGSSLWHMCS
                                )

                        )

                )

            [1] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/mgLibs/models/Repository.php
                    [line] => 67
                    [function] => select
                    [class] => MGModule\SSLCENTERWHMCS\mgLibs\MySQL\Query
                    [type] => ::
                    [args] => Array
                        (
                            [0] => 
                            [1] => mgfw_
                            [2] => Array
                                (
                                    [servertype] => GGSSLWHMCS
                                )

                            [3] => Array
                                (
                                )

                            [4] => 
                            [5] => 0
                        )

                )

            [2] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/models/whmcs/product/Products.php
                    [line] => 20
                    [function] => get
                    [class] => MGModule\SSLCENTERWHMCS\mgLibs\models\Repository
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [3] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/controllers/addon/admin/ApiConfiguration.php
                    [line] => 31
                    [function] => get
                    [class] => MGModule\SSLCENTERWHMCS\models\whmcs\product\Products
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [4] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/mgLibs/process/AbstractMainDriver.php
                    [line] => 193
                    [function] => indexHTML
                    [class] => MGModule\SSLCENTERWHMCS\controllers\addon\admin\ApiConfiguration
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [5] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/Addon.php
                    [line] => 310
                    [function] => runControler
                    [class] => MGModule\SSLCENTERWHMCS\mgLibs\process\AbstractMainDriver
                    [type] => ->
                    [args] => Array
                        (
                            [0] => ApiConfiguration
                            [1] => index
                            [2] => Array
                                (
                                    [module] => SSLCENTERWHMCS
                                    [mg-page] => apiConfiguration
                                )

                            [3] => HTML
                        )

                )

            [6] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/modules/addons/SSLCENTERWHMCS/SSLCENTERWHMCS.php
                    [line] => 52
                    [function] => getHTMLAdminPage
                    [class] => MGModule\SSLCENTERWHMCS\Addon
                    [type] => ::
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [module] => SSLCENTERWHMCS
                                    [mg-page] => apiConfiguration
                                )

                        )

                )

            [7] => Array
                (
                    [file] => /var/www/vhosts/example.com/httpdocs/whmcs/addonmodules.php
                    [line] => 0
                    [function] => SSLCENTERWHMCS_output
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [module] => SSLCENTERWHMCS
                                    [modulelink] => addonmodules.php?module=SSLCENTERWHMCS
                                    [access] => 4,1
                                    [version] => 2.0.0
                                )

                        )

                )

        )

    [previous:Exception:private] => 
)
```

Using:

PHP 7.2.18
Mariadb 5.5.60-MariaDB MariaDB Server
WHMCS 7.7.1


Thanks in advance.
