### ISSUE TITLE
Cannot set configuration on client area, error Email is incorrect after step two

### ISSUE THREAD

**Issue by satriaenur** [gogetssl/whmcs-addon#252]
**Describe the bug**
PositiveSSL in awaiting configuration status failed to setup the configuration due to error `Email is Incorrect` after submitting step two.
Every fields has been filled, already tried DCV Method Email, HTTP, HTTPS and DNS.

**To Reproduce**
1. Go to Service configuration after order paid and status Awaiting Configuration
2. Click on Configure Now
3. Fills all  the form
4. after step two it's coming back to step one with error `Email is Incorrect`

**Expected behavior**
SSL Certificate created, going to step three or anything

**Screenshots**
![image](https://github.com/gogetssl/whmcs-addon/assets/9528965/8757f9e3-2c38-4026-b6ad-f5986c8f8d93)

**WHMCS**
Version: 8.8.0
PHP Version: 7.3.33
Themes: RS Themes Lagom 2, version 2.2.2

**Comment by vlad-evg** [comment]
We are sorry for the delay in response. Many issues, including that one were fixed in the latest versions of the module. Please upgrade and let us know if you still face any issues
