### ISSUE TITLE
Dependency with DNSManager2

### ISSUE THREAD

**Issue by jozsefhabit** [gogetssl/whmcs-addon#264]
**Describe the bug**
Dependency with ModulesGarden DNSManager2 module. This will get an error as the latest DNSManager3 module documentation recommends to delete the old module.

**To Reproduce**
Try to validate with DNS. Will get an oops and this stack trace:

Error: Error: Class "MGModule\DNSManager2\loader" not found in /home/whmcs/public_html/docroot/includes/api/dnsmanager.php:18 Stack trace: #0 /home/whmcs/public_html/docroot/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): unknown() #1 /home/whmcs/public_html/docroot/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): WHMCS\Api\V1\Api->executeApiCall() #2 /home/whmcs/public_html/docroot/includes/functions.php(0): WHMCS\Api\V1\Api->call() #3 /home/whmcs/public_html/docroot/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(365): localAPI() #4 /home/whmcs/public_html/docroot/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(68): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->orderCertificate() #5 /home/whmcs/public_html/docroot/modules/addons/SSLCENTERWHMCS/eServices/provisioning/SSLStepThree.php(48): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->SSLStepThree() #6 /home/whmcs/public_html/docroot/modules/servers/SSLCENTERWHMCS/SSLCENTERWHMCS.php(70): MGModule\SSLCENTERWHMCS\eServices\provisioning\SSLStepThree->run() #7 /home/whmcs/public_html/docroot/configuressl.php(0): SSLCENTERWHMCS_SSLStepThree() #8 {main}

**Comment by jozsefhabit** [comment]
Hello,
is my ticket a duplication of [#263](https://github.com/gogetssl/whmcs-addon/issues/263)? Should I use the version that you provided over there (v2.10.1)?

**Comment by vlad-evg** [comment]
We got a response from our product team, this bug has been fixed in DNS Manager v3.4.1

Also make sure that you use the latest SSLCENTER 2.10.1

We tested it in this configuration and everything works fine. If there is any other error then you need to pass us the credentials to the client environment, then we will check it thoroughly.
