### ISSUE TITLE
SSL Order Summary in random places

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#269]
Hi there,

Is this a common issue or just happening on mine?

<img width="1199" alt="ssl-sidebar-upgrade" src="https://github.com/user-attachments/assets/64dc95df-cf02-442f-9b1d-fc9e7218c6d7">

This is a screen shop of the upgrade.php page in WHMCS when upgrading an unrelated VPS product.

Thanks,
C

**Comment by vlad-evg** [comment]
Hello. 

You are the first one who reported such issue, looks like template issues. You can create a ticket within your client area at my.gogetssl.com and provide us FTP + WHMCS Admin access to review that by developers
