### ISSUE TITLE
Problems with currencies and order summary

### ISSUE THREAD

**Issue by hexcom** [gogetssl/whmcs-addon#27]
**Describe the bug**
After using 2.0.x module there is a problem with order summary. We use 3 currencies and order summary ignores currency rate and each currency is counted 1:1. We have tested all versions from 2.0.x branch and on each version we have such problem. Before 2.0.x everything works fine. Product prices display correctly:

SS (main currency - correct prices): https://prnt.sc/mie7sl
SS (second currency - wrong order summary, product price correct): https://prnt.sc/mie8o9

When we choose continue, prices are taken from order summary which is wrong for each other currency than main:

SS( main currency - correct): https://prnt.sc/mieahb
SS (second currency - wrong final prices - ignores product price and currency): https://prnt.sc/mie9uf

**Comment by sergiurosca** [comment]
We experience the same problem. Please solve it asap.

**Comment by vlad-evg** [comment]
The fix in the devolopment now

**Comment by vlad-evg** [comment]
The fix [released now](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.0.5). Thank you for helping us

**Comment by speedhub1** [comment]
Hi, updates to 2.0.5 and the problem is stil there, using the latest whmcs version. Please help

**Comment by vlad-evg** [comment]
have you disabled and re-enabled SSL addon after the update? normally it requires to write all updates in SQL.

**Comment by speedhub1** [comment]
I have tried 3 times to disable the module and every time i get: "Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again."

**Comment by vlad-evg** [comment]
are you able to send WHMCS admin access and FTP as private message? so we can check what cause the problem?

**Comment by speedhub1** [comment]
Is team viewer an option?

**Comment by vlad-evg** [comment]
A bit harder, as would need to schedule all with Modules Garden

**Comment by vlad-evg** [comment]
Modules Garden checked this problem in the latest version of WHMCS, everything seems to work properly, please check

http://puu.sh/CTuGL/b866e21173.png
http://puu.sh/CTuGA/caf9098aca.png
