### ISSUE TITLE
Translation rules missing

### ISSUE THREAD

**Issue by thomashoeky** [gogetssl/whmcs-addon#29]
**Describe the bug**
Some translation rules are missing like:
"Configuration status: Awaiting configuration - Configure now"
I checked back on issue #7 but these rules do not seem to exist anymore

**To Reproduce**

1. Order a SSL certificate
2. Click on the product
3. See "Configuration status: Awaiting configuration - Configure now"

**Expected behavior**
A language rule in the lang file to translate this

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome

**Comment by vlad-evg** [comment]
Dear Thomas,

we would check that ASAP

**Comment by thomashoeky** [comment]
So it looks like part of the rules are in WHMCS's english.php but when changed are not used in the GGSSL module:
`$_LANG['sslconfigurenow'] = "Nu aanvragen";
$_LANG['sslstatus'] = "Status";`
The missing strings that I'm unable to find so far are:
`Order Type`
Select Renewal option in case you need renew existing SSL that expires soon. Certification center would `add up to 90-days left from Original order.`
`Please choose one...`
`New Order`
`Renewal`
The errors for not filling in details at the administrative contact:
`You did not enter x`
From the approval page:
`Domain`
`DCV Method`
`Email address`

**Comment by vlad-evg** [comment]
We checked the translations mentioned, in our test environment everything looks properly,  I present a few translations to confirm that they are in the module

Please choose one... - http://puu.sh/CTuSk/615be550e8.png - https://bugtrack.modulesgarden.com/custom-development/gogetssl/blob/master/modules/servers/SSLCENTERWHMCS/langs/english.php#L177

New Order - http://puu.sh/CTuVz/799a2ac1f3.png - https://bugtrack.modulesgarden.com/custom-development/gogetssl/blob/master/modules/servers/SSLCENTERWHMCS/langs/english.php#L85

Renewal - http://puu.sh/CTuVH/b66f287a4c.png - https://bugtrack.modulesgarden.com/custom-development/gogetssl/blob/master/modules/servers/SSLCENTERWHMCS/langs/english.php#L85

**Comment by thomashoeky** [comment]
What file and WHMCS version is this? I can not find "New Order" and "Renewal" like you do
