### ISSUE TITLE
TPL Override

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#3]
Is it possible to rewrite this file (\modules\addons\GGSSLWHMCS\templates\clientarea\default\scripts\orderType.tpl)?

I tried to customize it as
\templates\six2custom\modules\addons\GGSSLWHMCS\templates\clientarea\default\scripts\orderType.tpl after which I disconnected / connected the module, but I didn't succeed."

**Comment by ggs-victor** [comment]
can you please describe the reason you need to rewrite it? What exactly you plan to change?

**Comment by sergiurosca** [comment]
I want to move and edit this text https://www.screencast.com/t/8g8EuGNxRNw between the "Order type" label and the select tag.

**Comment by ggs-victor** [comment]
Issue fixed in 1.0.32 version.

The description has been moved between the "Order type" label and the select tag.
To change the content of the description, edit the file containing the translations located in your_whmcs/modules/servers/GGSSLWHMCS/langs/
