### ISSUE TITLE
Incorrect Price on Invoices when adding SANs to an Active SSL

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#30]
A user recently added a new SAN (using the Add/Change SAN feature) to its Active 2-year SSL which will expire within 4 months. Instead of creating an invoice with the SAN's price for 1 year (as it is invoiced by GGSSL), WHMCS recalculated the price and invoiced the client the amount for the remaining 4 months: https://screencast.com/t/fjkpigvF

Please fix this issue asap so that the SAN's invoices are created for 1 or 2 years, as necessary.

**Comment by vlad-evg** [comment]
Thank you, sending to development right now with critical status

**Comment by vlad-evg** [comment]
Here is what they replied:

I checked this problem in the latest version of WHMCS, everything seems to work properly, please check
http://puu.sh/CTuGL/b866e21173.png
http://puu.sh/CTuGA/caf9098aca.png
