### ISSUE TITLE
Renewal Invoices - No 'Pay' button

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#31]
After upgrading to the new version (see[ Issue #22](https://github.com/gogetssl/whmcs-addon/issues/22)), the renewal invoices received a "Pending Payment" status, but no active "Pay Now" button: https://screencast.com/t/wzErxdPOy

How to make the button display on the invoices?

**Comment by vlad-evg** [comment]
The fix is easy, please check that WIKI
https://github.com/gogetssl/whmcs-addon/wiki/Additional-Integration#renewal-invoices

**Comment by sergiurosca** [comment]
This issue is not closed - please open it back!

As you can easily see from the provided screenshot, the 'Payment Methods' drop-down is present on the invoice, but the 'Pay' button doesn't appear because it doesn't connect any of the payment methods. 

Please fix this asap.

**Comment by vlad-evg** [comment]
MG prepared a patch that does not require the addition of integration code.  
https://www.gogetssl.com/skin/i/gogetssl-2.0.6_patch.zip

WHMCS, when the invoice has the status of Payment Pending, it blocks the possibility of payment, so the status will be changed temporarily.

In the system, the invoice has the Payment Pending status all the time http://puu.sh/CVSSa/93998131df.png , however, when you go to the invoice view, the status is temporarily changed to Unpaid  http://puu.sh/CVSRT/0aa8fc97b8.png

**Comment by vlad-evg** [comment]
Does that solved your issue?

**Comment by sergiurosca** [comment]
Yes, thank you!
