### ISSUE TITLE
[v2] Addon Module Activated SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `mgfw_SSLCENTER_user_commission` add constraint `mgfw_sslcenter_user_commission_client_id_foreign` foreign key (`client_id`) references `tblclients` (`id`) on delete cascade)

### ISSUE THREAD

**Issue by yashodhank** [gogetssl/whmcs-addon#36]
**Describe the bug**
```
Addon Module Activated
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `mgfw_SSLCENTER_user_commission` add constraint `mgfw_sslcenter_user_commission_client_id_foreign` foreign key (`client_id`) references `tblclients` (`id`) on delete cascade)
```

**To Reproduce**
1. Go to 'Addon Modules'
2. Click on 'Activate'
3. See error

**Expected behavior**
There should not be any error, while activating new module.

**Screenshots**
![image](https://user-images.githubusercontent.com/1083792/57842300-d966f780-77e9-11e9-9a08-e455b346c75e.png)

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.4
 - Browser: chrome
 - Version: 74

**Additional context**
Tested with v2.0.0 and 2.0.8a release.
Error first encountered when I was performing manual upgrade from v1.0.42 to v2.0.0

**WHMCS**
- Version: 7.7.1

**Comment by vlad-evg** [comment]
We are sorry for the delay and missing your issue. 
Have you completed Migration to 2.x steps, an error always appears if missing that migration 
https://github.com/gogetssl/whmcs-addon/wiki/Migration-to-v.2
