### ISSUE TITLE
"Order Type" translate

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#38]
During the SSL configuration, on the first step, there is this section:

> Order Type
> Select Renewal option in case you need renew existing SSL that expires soon. Certification center would add up to 90-days left from Original order.

I not found where i can translate this, i not found this text inn module language files or in WHMCS lang files.

Do you know where i need to find it?

![Képkivágás](https://user-images.githubusercontent.com/690503/58809082-89769600-861b-11e9-9f09-7a69b2c5c430.PNG)

**Comment by vlad-evg** [comment]
We will check ASAP

**Comment by vlad-evg** [comment]
The translation exists already:

$_LANG['selectOrderTypeDescritpion']    = 'Select Renewal option in case you need renew existing SSL that expires soon. Certification center would add up to 90-days left from Original order.';
