### ISSUE TITLE
Hook for validation

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#39]
Hello,

Is it possible to add a hook, what run after the client choosed the validation type (http, dns, etc)?

We would like to implement a solution when we can add the necessary DNS record or HTTP file when domain name hosted in our system.

It will be good, if the hook pass the validation method, and the contents what need.

**Comment by vlad-evg** [comment]
Hello,

we are checking the option

**Comment by vlad-evg** [comment]
Adding such a function will be very complicated and time-consuming. For this functionality to work properly, hosting would also be purchased through WHMCS (eg via a cPanel account). Then we would be able to connect to the cPanel API and add a file or DNS record.
Such modification will take about 30 - 40h and will cost us $1500 - $2000.

If that is really needed, we can go for it...

**Comment by charliehu** [comment]
No-no. I need only one hook what run after when client finished the SSL wizard, where i can put my own PHP codes to do this. No need to validate anything, or connect to anywhere.

**Comment by thomashoeky** [comment]
I think this should not be implemented in the gogetssl WHMCS addon, but in the gogetssl API itself:
https://github.com/gogetssl/api/wiki
something like getValidationMethod with the DNS validation record, or email which is used so he/she can implement it with their own code

**Comment by vlad-evg** [comment]
We will add that to our API, it will be scheduled to Q4 2019
