### ISSUE TITLE
ssl summary panel

### ISSUE THREAD

**Issue by hammedsadeghi** [gogetssl/whmcs-addon#4]
i had updated your whmcs module and i see your module add panel in my template automatically
i want to know can i manage this panel for showing only after user login in her panel ?
and whats path of that file ?

**Comment by ggs-victor** [comment]
Thank you, we will ask developers to make an update to hide the summary if not logged in. Also, there will be an option to enable/disable feature from admin area

**Comment by hammedsadeghi** [comment]
while you dont release this update can i manage it from source?

**Comment by ggs-victor** [comment]
Problem fixed in [1.0.33 release](https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.33), Option to turn ON/OFF sidebar from Addon settings added. Hide SSL summary when user not Logged in.
