### ISSUE TITLE
Sync due date with cert expiry date

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#41]
Hi,

Is it possible to add a feature, to sync due date to the certificate expiry date? For example, comodo always add some extra day to the expiry date, and when a certificate renewd many time, there is multiple months difference beetwen the due date and the real expiry date.

**Comment by vlad-evg** [comment]
Hello,

Yes, that sounds reasonable, we would implement it. I will let you know once done.
Thank you for helping us to make it better.

**Comment by thomashoeky** [comment]
Please let the admin set the difference in days, this would be great to get all services on a single invoice (domain sync 31 days, gogetssl sync 31 days, and the hosting on the same date)

**Comment by vlad-evg** [comment]
So all I need to do is to add a Amount days (Sync Due Date) field to the module's configuration. Due date will synchronize with the expiration date of the certificate + value from the field Amount days (Sync Due Date)

For example:
Amount days (Sync Due Date) = 3
Cert expiry date = 26-06-2019
So Due Date it will have a value 29-06-2019
Can you confirm?
