### ISSUE TITLE
Generate CSR got {"success":0,"msg":"$_LANG['Instance is not set']"}

### ISSUE THREAD

**Issue by louishot** [gogetssl/whmcs-addon#42]
Hello,

Why Generate CSR got {"success":0,"msg":"$_LANG['Instance is not set']"}
http://prntscr.com/o59o5u

**Comment by vlad-evg** [comment]
we will check

**Comment by shabsta** [comment]
Any update on this issue as of yet?

**Comment by vlad-evg** [comment]
MG replied, "I cannot recreate this issue. Could you ask the client for credentials to the environment where this issue is?"
