### ISSUE TITLE
Order Type Missing from SSL Configuration Page

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#43]
![Capture1](https://user-images.githubusercontent.com/43058981/60125484-2e544100-978c-11e9-8929-a31d0fff2463.PNG)
![Capture](https://user-images.githubusercontent.com/43058981/60125486-2eecd780-978c-11e9-887f-4c6caf9c3e53.PNG)

**Describe the bug**
After accepting a new ssl order (Multiple vendors tested on multiple whmcs installations), impersonating the user and attempting to configure the certificate on the ssl configuration screen the order type is missing (Renewal / New Order) and we're unable to proceed.

This issue started today, not sure if its due to an error with GGSSL API?

**Additional context**

**Comment by vlad-evg** [comment]
That error appears when the API password is wrong OR expired. can you please [regenerate](https://github.com/gogetssl/whmcs-addon/wiki/API-Configuration) API pass and retry?

**Comment by shabsta** [comment]
We have already generated a new API password.

Issue still exists.

We have three systems connecting to the api service at GGSSL
Two whmcs services which cannot show order type and third system which
connects to api (custom coded)
The third system is returning
The request was aborted: Could not create SSL/TLS secure channel.

**Comment by shabsta** [comment]
Have you had a chance to look into this?

We are still unable to process new orders via whmcs

**Comment by vlad-evg** [comment]
Yes, we are investigating. The issue was TLS 1.0, TLS 1.1, which we stop allowing, now TLS1.1 is back for 30 days

**Comment by shabsta** [comment]
A notice prior to the change would have been “nice”, or a notice posted
about the change after things were changed would have been “nice”.

Notifying tech support at GGSSL about the change would have been “nice”

All ssl orders and renewals have failed for the last 2 days because of this!

You guys need to get your customer notifications sorted, it’s been a
feature that has lacked for years.

**Comment by vlad-evg** [comment]
that was unexpected, we migrated production server to new infrastructure with multiple updates on config files. System administrators missed that TLS 1.0 and TLS 1.1 would rise that critical problem. I do agree with you that it is not professional and we are building now new notification system to resellers with some push messages or SMS if anything critical requires.

**Comment by shabsta** [comment]
Thanks for the response

Will the module be update to accommodate these changes?
I see there was a release posted a few moments ago but the change log makes no reference to TLS versions

**Comment by vlad-evg** [comment]
It is not related to the module at all, it is related ONLY to your server configuration.  The latest release has a critical fix for CSR generator, as we have more strict CSR decoder now to have less Pending orders

**Comment by shabsta** [comment]
Please update me when the change has been reverted, as we're still receiving the same error on ssl configuration

![Capture](https://user-images.githubusercontent.com/43058981/60250496-0d443b00-98c7-11e9-9ded-9dd426923ffd.PNG)

**Comment by shabsta** [comment]
Please also confirm the version of TLS that must be used within 30 days so that I can pass this information on to our developers

**Comment by vlad-evg** [comment]
TLS 1.2 please

**Comment by shabsta** [comment]
Using the code below, I have confirmed that we are using TLS 1.2

`<?php

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://www.howsmyssl.com/a/check");
curl_setopt($ch, CURLOPT_SSLVERSION, 6);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);
$tlsVer = json_decode($response, true);
echo "<h1>Your TLS version is: <u>" . ( $tlsVer['tls_version'] ? $tlsVer['tls_version'] : 'no TLS support' ) . "</u></h1>";`
[Capture](https://user-images.githubusercontent.com/43058981/60251849-99eff880-98c9-11e9-9771-e0ebc868f3de.PNG)

Based on version of tls supported by our server, and that the module is still throwing an error after you advised that the changes have been reverted, I suspect the issue lies somewhere else.

Waiting on my developer to confirm if we're still experiencing issues on other platforms that dont use whmcs - will update you

**Comment by shabsta** [comment]
Confirmed that all systems are failing to connect to gogetssl api - please
URGENTLY get this resolved


yep: ID LogLevel LogSource LogMessage Modified
45318179 Exception Service.GetRequest The request was aborted: Could not
create SSL/TLS secure channel. 2019-06-27 11:06:02.120

**Comment by thomashoeky** [comment]
Youre echo'ing a set string and not the response. TLS 1.1 and below should have been disabled since june 2018 already. There are no issues with people using the proper tls version so it does look like you are using an older version

**Comment by vlad-evg** [comment]
Can you please do  curl -X POST https://my.gogetssl.com/api/auth/  and send result of that?

**Comment by shabsta** [comment]
> Youre echo'ing a set string and not the response. TLS 1.1 and below should have been disabled since june 2018 already. There are no issues with people using the proper tls version so it does look like you are using an older version
@thomashoeky 
Do you have any suggestions or are you able to point me in the right direction?
This doesn't account for other systems on other servers also failing to connect.

@vlad-evg 
Result of post using test file that was supplied
`array ( 'version_number' => 471808, 'age' => 3, 'features' => 266141, 'ssl_version_number' => 0, 'version' => '7.51.0', 'host' => 'x86_64-pc-win32', 'ssl_version' => 'OpenSSL/1.0.2j', 'libz_version' => '1.2.8', 'protocols' => array ( 0 => 'dict', 1 => 'file', 2 => 'ftp', 3 => 'ftps', 4 => 'gopher', 5 => 'http', 6 => 'https', 7 => 'imap', 8 => 'imaps', 9 => 'ldap', 10 => 'pop3', 11 => 'pop3s', 12 => 'rtsp', 13 => 'scp', 14 => 'sftp', 15 => 'smtp', 16 => 'smtps', 17 => 'telnet', 18 => 'tftp', ), ) '{"error":true,"message":"Username and\\/or password not supplied","description":"This request requires username and password"}' array ( 'url' => 'https://my.gogetssl.com/api/auth/', 'content_type' => 'application/json; charset=utf-8', 'http_code' => 200, 'header_size' => 461, 'request_size' => 63, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 1.0939999999999999, 'namelookup_time' => 0.32799999999999996, 'connect_time' => 0.51600000000000001, 'pretransfer_time' => 0.89100000000000001, 'size_upload' => 0.0, 'size_download' => 125.0, 'speed_download' => 114.0, 'speed_upload' => 0.0, 'download_content_length' => -1.0, 'upload_content_length' => -1.0, 'starttransfer_time' => 1.0939999999999999, 'redirect_time' => 0.0, 'redirect_url' => '', 'primary_ip' => '18.184.47.5', 'certinfo' => array ( ), 'primary_port' => 443, 'local_ip' => '197.81.192.37', 'local_port' => 45011, )`

**Comment by vlad-evg** [comment]
New version [2.1.3 released](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.1.3) with fix of that problem. Hope that would solve all issues
