### ISSUE TITLE
API Order ID

### ISSUE THREAD

**Issue by SBerezjuk** [gogetssl/whmcs-addon#45]
Hello,

When customer renews an SSL certificate GoGet changes API Order ID of renewed SSL on their side, however the WHMCS module doen't update the SSLCenter API Order ID in WHMCS. 

Is there any way to resolve ti? 

Thank you.

**Comment by vlad-evg** [comment]
Hello,

every renewal would create new order in WHMCS and new order at our system, that is how it works. The renewal should NOT do any changes to original order that you renew

**Comment by SBerezjuk** [comment]
Does it work for SSL certificates which were migrated from the module version 1.4+ to 2+?

**Comment by charliehu** [comment]
I not experienced this, when client pay the invoice, module sent a renewal
request to gogetssl and modify the product due date, but there is no new
order.

**Comment by vlad-evg** [comment]
> Does it work for SSL certificates which were migrated from the module version 1.4+ to 2+?
Yes, there should be not issues with that.

**Comment by SBerezjuk** [comment]
I have to reopen this request because we still have this issue. Client renewed an SSL certificate, new order was created for this SSL in my.gogetssl.com, but no new orders were added on the billing side. Now the SSL is marked as terminated in our billing, however the next due date is set to "22.09.2020" and also, in the SSL details it shows:
Order Status: Expired
SSLCenter API Order ID: OLD ID

How to resolve this issue?
