### ISSUE TITLE
Problem with renewal of imported SSL certificate

### ISSUE THREAD

**Issue by SBerezjuk** [gogetssl/whmcs-addon#48]
Hello,

We imported an SSL using the the option SSLCENTER WHMCS > Import SSL Order. Now we need to renew it, however we get this error in WHMCS:

==============================

Module Command ErrorModule Command Error
Wrong approver email() for *

==============================

We tried to investigate this issue and found that there are no any records regarding the imported SSL in the WHMCS database in the table  tblsslorders. 

Could you please verify this issue and resolve it? 

Thank you!

**Comment by vlad-evg** [comment]
Checking...

**Comment by vlad-evg** [comment]
Developers replied:

"Unfortunately, I cannot recreate this issue. Could you please send credentials to the environment where this issue occurs?"

**Comment by SBerezjuk** [comment]
I cannot send you any credentials, however we found that the renewal record has been created in  the table tblsslorders with such settings:
{"order_type":"renew"},"approveremail":null}

We manually updated the approveremail from null to admin@domain and were able to renew the SSL.
