### ISSUE TITLE
After updating to v2.1.3 - Unable to find Template:fatal.tpl is thrown on module page

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#49]
**Describe the bug**
After updating to v2.1.3 - Unable to find Template:fatal.tpl is thrown on module page

```
Full error
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

If the problem persists, please contact us.

« Back to Homepage

For additional assistance, please reference the WHMCS TroubleShooting Guide »

MGModule\SSLCENTERWHMCS\mgLibs\exceptions\System: Unable to find Template:fatal.tpl in D:\Domains\<redacted>\wwwroot\modules\addons\SSLCENTERWHMCS\mgLibs\Smarty.php:126
Stack trace:
#0 D:\Domains\<redacted>\wwwroot\modules\addons\SSLCENTERWHMCS\Addon.php(359): MGModule\SSLCENTERWHMCS\mgLibs\Smarty->view('fatal', Array)
#1 D:\Domains\<redacted>\wwwroot\modules\addons\SSLCENTERWHMCS\SSLCENTERWHMCS.php(52): MGModule\SSLCENTERWHMCS\Addon::getHTMLAdminPage(Array)
#2 D:\Domains\<redacted>\wwwroot\zadomains_admin\addonmodules.php(0): SSLCENTERWHMCS_output(Array)
#3 {main}
```

**To Reproduce**
1. Full upgrade by removing old files and copying new files
2. Click on SSLCenter under modules
3. See error

**Comment by vlad-evg** [comment]
checking :(((

**Comment by vlad-evg** [comment]
I checked it in my test environment and in https://client.za.domains/zadomains_admin/ it looks good. Could you please give me access to the environment where this issue occurs?

**Comment by shabsta** [comment]
Please remove that URL from the public post
I had restore from backup after attempting to update the project. Are you able to contact me directly and we can work together on it as duplicating the issue brings whmcs down

**Comment by vlad-evg** [comment]
Sure, please send us an internal ticket from Client area and we would connect you with MG
