### ISSUE TITLE
CSR error without error messages

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#5]
Hello,

If i ordering a Comodo Positice SSL wildcard, your system require a certificate with *.domain.tld. When the CSR contain only the domain, after step2 the WHMCS modul going back to step1, but it not displaying any error messages (my.gogetssl.com display the error messages, CSR need to containt *.domain.tld  as domain).

**Comment by ggs-victor** [comment]
Thank you, we would try to solve that problem ASAP

**Comment by ggs-victor** [comment]
Can you provide login information to the environment where this problem occurs?
I am referring to WHMCS administrator and FTP server data.

I am not able to reproduce this problem in our environments (an error is displayed correctly). I think that this may be related to the system template being used.

You can provide it in support Ticket from Client area

**Comment by charliehu** [comment]
Hi

Yes, we using costum template. I will check it with original six theme.

**Comment by ggs-victor** [comment]
Let us know if the issue persists with SIX.
