### ISSUE TITLE
Sync - SSL in WHMCS is Active, yet in GGSSL is Expired

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#50]
Hi There,

We have many SSL in WHMCS as Active, but, really they are expired. 

Is there a command we can run to sync them up manually? 

Thanks for any help.

Sam

**Comment by vlad-evg** [comment]
Dear Sam,

To synchronize the certificates manually you have to run the command
* php -q /your_whmcs_dir/modules/addons/SSLCENTERWHMCS/cron/cron.php via the ssh
* or go to URL your_whmcs_url/modules/addons/SSLCENTERWHMCS/cron/cron.php 

However, it is recommended to add a new line to the crontab
* 0 */1 * * * php -q /your_whmcs_dir/modules/addons/SSLCENTERWHMCS/cron/cron.php
Then the certificates will be synchronized every hour.

**Comment by qhgh** [comment]
Hi there,

Thanks for the reply. 

We already have this cron;

`0 */1 * * * php -q /home/user/public_html/modules/addons/GGSSLWHMCS/cron/cron.php`

It seems to run fine, but the SSL's still say active in WHMCS when they have actually expired. 

Would you have any more advice on what I can check?

Thanks.

**Comment by qhgh** [comment]
Hi there,

We've now upgrade to latest module and ran php -q /home/whmcs/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php

But still expired and cancelled SSLs show as active in WHMCS.

Can you please help any further?

Thanks

Kev

**Comment by vlad-evg** [comment]
Checking now with developers

**Comment by vlad-evg** [comment]
Please update to 2.1.0 and let us know if any more problems occurs
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.1.10

**Comment by qhgh** [comment]
Hi, 

I've uploaded the new files and ran:

php -q /home/user/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php

But we see the same issue.

Here is an example screen shot: http://prntscr.com/p28wsk

I hope this helps.

Thanks.

**Comment by vlad-evg** [comment]
:((( Running back to developers

**Comment by vlad-evg** [comment]
Developers are not able to recreate the issue. Please provide FTP and WHMCS admin access via the ticket to make deeper analysis

**Comment by qhgh** [comment]
Hi Vlad, 

Okay, I've raised ticket: VJK-745-89171

Thanks for the help :)

**Comment by vlad-evg** [comment]
we really hope now you will have no issue :/
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.1.12
