### ISSUE TITLE
CSR Generation issue

### ISSUE THREAD

**Issue by SBerezjuk** [gogetssl/whmcs-addon#51]
Hello,
If customer generates CSR via WHMCS and then continue to configure SSL configuration he gets such error:
CSR is not valid. CSR should end with `-----END CERTIFICATE REQUEST-----...`

We checked this issue and found that the CSR is generated with 4 "-" after REQUEST. It looks like:
-----END CERTIFICATE REQUEST----

Please fix this.

**Comment by vlad-evg** [comment]
What is your current WHMCS SSL addon? Can you show us example of the CSR that has problems?

**Comment by SBerezjuk** [comment]
2.1.2

Just generated a new CSR:

-----BEGIN CERTIFICATE REQUEST-----
MIIC0zCCAbsCAQAwgY0xCzAJBgNVBAYTAlVBMREwDwYDVQQIDAhWaW5uaXRzYTER
MA8GA1UEBwwIVmlubml0c2ExEDAOBgNVBAoMB0hvc3RpbmcxEDAOBgNVBAsMB0hv
c3RpbmcxEzARBgNVBAMMCmhvc3RpZy5jb20xHzAdBgkqhkiG9w0BCQEWEGFkbWlu
QGhvc3RpZy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDA0T0N
ehm9kJAyxJGUdbX327rSjPDAP2yo9o1dntSQofIsJHils89gOtXrMoV6H4FG9AJr
yhazvmcnisqcClpNnNUPtk6NI2B/CwYCmLHsAWscnLM1hGHiUKWeQPfF5/KJRG6c
faWh0ab/oNL11prTrret0ysGt3Dwg4LhNZdoWszT3erpbJ+DK3AWjaXk/mCaSIsg
OwarxenMIzKVEWT8q3mx1qYGWiDh1dZgHguZ81dEMqo7AA6b5ZeSYVbTMHFnY80U
+P7Q+Z8Qre/s56aeShE/YrYMcXbd4TLctnR9JiYXKXNenfAy8AZx/dKN3TSlmy3S
Kh5kMMWPTW/tAd7dAgMBAAGgADANBgkqhkiG9w0BAQUFAAOCAQEASB3vcmBN971W
lfXnvII80kmBCLOGIrxq8SYKQ+I/HB1+ooID8LC4WcOjwzLt+tJfn/ADOsMDHZOJ
QPA5bANgXLRsvI3ap0D16iD6kX7gngNboGismsm/9uFs/Pcm/7dbbknEaoKRC+NV
JGMBn9LBw1hNXg0EylGvLFNJ8c3ExURL9fNq3KjYVDebh1h21ZMpw1fWGuhuC0OT
RoJy72cxCZeoIOdzhXA8ktmJ66BEqSo2I0D/bs3kFdFbVeY77Rx8TP+FawlGkeAb
r1VC28o8RfU2+ebYYu0zJpdyf6nWtu7h/xwjxQfoFvkHcvcqV/z26UUkDpkz//+U
+zBSkhMNmA==
-----END CERTIFICATE REQUEST----

**Comment by vlad-evg** [comment]
I just tried [2.1.3a](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.1.3a) and all is correct. Can you please retry?

**Comment by SBerezjuk** [comment]
Yes, started to generate CSR correctly after update to 2.1.3a. Thank you.
