### ISSUE TITLE
SANs have the wrong price

### ISSUE THREAD

**Issue by munteanu210** [gogetssl/whmcs-addon#54]
We reported this issue/bug some time ago: https://github.com/gogetssl/whmcs-addon/issues/30

You fixed it, but it reappeared in WHMCS addon version 2.1.3a which you released 24 days ago: https://github.com/gogetssl/whmcs-addon/releases/tag/v2.1.3a

Here is an example where we saw it on our addon. We have a $10 charge per SAN for a particular certificate. A customer bought a SAN and was charged only $3.01 instead of $10: https://screencast.com/t/1OgR08Za

Could you please fix this error?

**Comment by vlad-evg** [comment]
We will check it

**Comment by vlad-evg** [comment]
We are preparing new custom feature for WHMCS that will allow to upgrade products with correct pricing. ETA 7-10 days

**Comment by munteanu210** [comment]
@vlad-evg sounds good! We look forward to getting it ASAP.

**Comment by vlad-evg** [comment]
Finally, the [2.2.1](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.1) release is ready. We and MG already tested it. We hope all will be good. Thank you for patience.
