### ISSUE TITLE
Error: can't find invoice for free products

### ISSUE THREAD

**Issue by bady1985** [gogetssl/whmcs-addon#6]
When the client orders a free Trial certificate, he becomes an Error after he has opted for the verification option that the invoice can't be found. What is clear because whmcs doen't create invoices for free free products.

I think that was introduced with the "Add domain information to an existing invoice after the end customer has configured the certificate." feature.

**Comment by ggs-victor** [comment]
Thank you, we would investigate ASAP

**Comment by ggs-victor** [comment]
The issue fixed with 1.0.35 release, please (download it)[https://github.com/gogetssl/whmcs-addon/releases/tag/v1.0.35]
