### ISSUE TITLE
Generate CSR button not show

### ISSUE THREAD

**Issue by mohikan68** [gogetssl/whmcs-addon#62]
**Describe the bug**
Generate CSR button not show

**Screenshots**
http://prntscr.com/p26b6k

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 63.0.3368.53

**Comment by vlad-evg** [comment]
Hello,

what is your current SSL addon version?

**Comment by mohikan68** [comment]
> Hello,
> 
> what is your current SSL addon version?

v2.1.9 last version

**Comment by vlad-evg** [comment]
Please send us FTP access and WHMCS admin via the ticket, we will urgently check that with developers :/

**Comment by mohikan68** [comment]
> Please send us FTP access and WHMCS admin via the ticket, we will urgently check that with developers :/

Ticket Number: #YLQ-275-10485 Thanks.

**Comment by vlad-evg** [comment]
You are using a custom template, the button is displayed in the default bootstrap popup, in the .panel-footer section, but this section has the display: none attribute set. https://www.screencast.com/t/inkZ9rvTCdR
