### ISSUE TITLE
Translation rules missing

### ISSUE THREAD

**Issue by thomashoeky** [gogetssl/whmcs-addon#7]
**Describe the bug**

**To Reproduce**
1. Order a SSL certificate
2. Click on the product
3. See "Configuration status: Awaiting configuration - Configure now"

**Expected behavior**
A language rule in the lang file to translate this

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by thomashoeky** [comment]
Looks like translation rules for the client area do not exist yet, or I cant find them in the lang files

**Comment by ggs-victor** [comment]
Thank you, we would check ASAP

**Comment by ggs-victor** [comment]
Mentioned translation rules already exist and is localised in /your_whmcs_path/modules/servers/GGSSLWHMCS/langs/english.php :

$_LANG['serverCA']['home']['configurationStatus'] = 'Configuration Status';
$_LANG['serverCA']['home']['Awaiting Configuration'] = 'Awaiting Configuration';
$_LANG['serverCA']['home']['configureNow'] = 'Configure Now';

You can edit the above-mentioned file or create a file overwriting only selected translation rules by creating a corresponding language file in the overrides directory: /your_whmcs_path/modules/servers/GGSSLWHMCS/langs/overrides/

Let us know if more questions...

**Comment by thomashoeky** [comment]
Hello, these rules do not seem to exist in the current version (SSL CENTER WHMCS)
