### ISSUE TITLE
SSL Renewal Issue

### ISSUE THREAD

**Issue by SBerezjuk** [gogetssl/whmcs-addon#70]
Hello,

This is related to the issue reported here:
https://github.com/gogetssl/whmcs-addon/issues/45

We still have this issue. Client renewed an SSL certificate, new order was created for this SSL in my.gogetssl.com, but no new orders were added on the billing side. Now the SSL is marked as terminated in our billing, however the next due date is set to "22.09.2020" and also, in the SSL details it shows:
Order Status: Expired
SSLCenter API Order ID: OLD ID

How to resolve this issue?

**Comment by vlad-evg** [comment]
Hello,

"but no new orders were added on the billing side." - you mean renewal order arrived to us via API, but you do not see any renewal order at WHMCS client area?

**Comment by SBerezjuk** [comment]
Yes, exactly.

**Comment by vlad-evg** [comment]
Well, that sounds very strange. We receive no claims like that. WHMCS do not have option to send order for renewal with an order. What is your current SSL addon version? Can you send us admin access via the Ticket and details of order/domain name?

**Comment by SBerezjuk** [comment]
OK, I will open a support ticket via the gogetsll client area.
