### ISSUE TITLE
Approval email won't appear after fill in the ssl activation form

### ISSUE THREAD

**Issue by Sherly02** [gogetssl/whmcs-addon#71]
We have a problem about activating ssl, 

The client can't get their email for approval email while activating their ssl.
![email](https://user-images.githubusercontent.com/35279297/65478592-80545200-deb4-11e9-8c71-badc903b0726.png)

After we checked it, we got that the csr can't be use. 
The client generated their csr from generate button inside the ssl activation form.
![csrgen](https://user-images.githubusercontent.com/35279297/65478534-526f0d80-deb4-11e9-8b02-094accc1c569.png)

But, when we use the another csr generator, the email is appear.

**Comment by vlad-evg** [comment]
Hello,

the issue was fixed with [2.1.5 release](https://github.com/gogetssl/whmcs-addon/releases), please update to latest module and retry

**Comment by Sherly02** [comment]
OK , we will update it soon. Thanks
