### ISSUE TITLE
Admin area 'View Certificate' button

### ISSUE THREAD

**Issue by jozsefhabit** [gogetssl/whmcs-addon#75]
**Describe the bug**
Clicking on the Admin area 'View Certificate' button shows the CA certificate chain only. Instead it should show the certificate itself (or with the CA cert chain).

**To Reproduce**
1. Go to 'Admin area' Certificate product page
2. Click on 'View Certificate' button

**Comment by vlad-evg** [comment]
What is your current SSL addon version?

**Comment by jozsefhabit** [comment]
2.2.4, just updated yesterday.


HÁBIT József          | Jozsef HABIT
ZeroTime Services Kft | ZeroTime Services Ltd.

**Comment by vlad-evg** [comment]
The new release has a fix for that https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.5
