### ISSUE TITLE
Send Certificate Email Template

### ISSUE THREAD

**Issue by jozsefhabit** [gogetssl/whmcs-addon#76]
**Describe the bug**
The "Send Certificate Email Template" contains the {$ssl_certyficate} variable. This variable only contains the CA chain, thus it sends only the CA chain to the customer.

**Expected behavior**
It should send the certificate itself AND the CA chain.

**Comment by vlad-evg** [comment]
It was fixed with 2.2.2 version
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.2
