### ISSUE TITLE
Custom Icon not working

### ISSUE THREAD

**Issue by DougK94** [gogetssl/whmcs-addon#79]
Made the changes described here https://github.com/gogetssl/whmcs-addon/wiki/Additional-Integration

Result is a blank dark circle with no icon displayed.

**Comment by vlad-evg** [comment]
Maybe you are not using default style and have no icons on the server. Need more information. Try use Chrome developer tools (f12) to see what is inside the code

**Comment by DougK94** [comment]
Thank you for the speedy reply.

These changes have been made to both the default Six template along with my custom theme that is based on Six.  There are no icons showing for any products, including SSL's using either theme.

I am not sure what I am looking for using the Chrome developer code.

**Comment by vlad-evg** [comment]
Please send us WHMCS admin access to check your issue. You can send access via the Ticket
