### ISSUE TITLE
'Can not fetch Web Server List' error

### ISSUE THREAD

**Issue by sergiurosca** [gogetssl/whmcs-addon#8]
When configuring the certificate, the following error occurs: https://www.screencast.com/t/k3bNMonj

The web server list doesn't load. 

How to solve this issue?

**Comment by vlad-evg** [comment]
The most common issue is the wrong API password.  Please try generate new API password and paste to SSL add-on. Here is [manual](https://github.com/gogetssl/whmcs-addon/wiki/API-Configuration)
