### ISSUE TITLE
Option to disable entries to the Activity Log

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#81]
The Activity Log is filled with entries from SSLCENTER WHMCS.
In under a year, there has been written more than 260.000 lines - and that's just from the addon. That's a third of everything in our Activity Log.

It would be great with a feature to disable logging as it's mostly non-important information in there.

**Comment by vlad-evg** [comment]
WHMCS saves Activity log even if the Log Errors field is not checked. However, the user can set the maximum number of logs in WHMCS, please go to Setup -> General Settings -> General -> Limit Activity Log.

**Comment by DennisSkov** [comment]
@vlad-evg it's not error logs. It's just information like this: "SSLCENTER WHMCS: Certificate Sender completed. The number of messages sent: 0".
Logging to the activity log **only** happens if you use the logActivity function.

**Comment by vlad-evg** [comment]
The new release should have an option to enable/disable that. We have scheduled the development. Thank you for the suggestion

**Comment by vlad-evg** [comment]
New Release ready with a feature to "FORCE stop" of logging module activity. https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.7

**Comment by w3servicesdotnet** [comment]
What does this mean? What feature?

Please share steps to renew order.

From


*Sunil YFounder & Cloud Solution Architect*
*-----------------------------------------------------------------------*


<https://members.w3services.net/viewticket.php?tid=233326&c=JBbCobNW&feedback=1>

**Comment by DennisSkov** [comment]
@w3servicesdotnet this issue was for disabling logging. It has nothing to the with renewing orders.

**Comment by DennisSkov** [comment]
@vlad-evg I've now updated the module twice, but still see version as 2.2.5. I don't see the option in the module settings either.

**Comment by cenourinha** [comment]
Hi! Is this working for anyone? The logs keep getting saved if i tick/untick the option "Tick this field to save logs".

**Comment by cenourinha** [comment]
Dear @vlad-evg,

At the "mgfw_SSLCENTER_api_configuration" table i see that if we check the "Activity log" option on the module settings the "save_activity_logs" is filled with "1" and if we uncheck the option, the "save_activity_logs" is set to "0".

But then, when the function savelogActivitySSLCenter() is executed, the option validation does seem to check only if the option is set (isset) and if the configuration is not empty, making the logs to be always saved.

https://github.com/gogetssl/whmcs-addon/blob/5de073ea6ea29db375ae697829897122ce34a5e1/modules/addons/SSLCENTERWHMCS/eHelpers/Whmcs.php#L18

Can you please check this?

**Comment by vlad-evg** [comment]
Yes, sure. We will investigate

**Comment by vlad-evg** [comment]
If the option is not checked, the value in the database will be 0, but the logs will not be saved anyway because apart from "isset" it is also "!empty". And if the value of the field is 0 (means empty), the condition will not be met and the logs will not be saved.
