### ISSUE TITLE
approver email does not show up

### ISSUE THREAD

**Issue by hendranata** [gogetssl/whmcs-addon#82]
when new order place..
approver email does not show up..
i am using module version 2.1.4 SSLCENTER

**Comment by hendranata** [comment]
https://ibb.co/t384DSP

**Comment by hendranata** [comment]
i have update using latest version: v2.2.5
also same.. see screenshot above..

**Comment by hendranata** [comment]
also i notice in the latest module.. 
web server type only show: "IIS" and "any other"
does it true?
it was not same with previous version

**Comment by hendranata** [comment]
okay seems i know the issue...

CSR Error: Common name(kasihcyber.wifi) from your CSR is invalid. Please provide valid CSR code with valid TLDN (Top-Level-Domain-Name) common name.

when CSR is invalid.. they do not show the error message regarding CSR is invalid.. that is why make it confusing ...and email validation does not appear..
hope this bug will be fix soon

**Comment by vlad-evg** [comment]
Yes, we are trying to push MG to use our own decoder and TLD validation, to prevent problems like that. Regarding the Server Types, yes, that is correct ,basically even that is not required as all certs are the same

**Comment by hendranata** [comment]
hope will any update for this case

**Comment by vlad-evg** [comment]
Can you please send us CSR that cause an issue?

**Comment by hendranata** [comment]
any update?

**Comment by vlad-evg** [comment]
Should work in latest SSL addon. Please try

**Comment by hendranata** [comment]
ok thanks
    On Thursday, November 21, 2019, 12:17:06 AM GMT+7, Vladislavs Dovoreckis <notifications@github.com> wrote:  
 
 
Should work in latest SSL addon. Please try
