### ISSUE TITLE
$version not upgraded

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#87]
In modules/addons/SSLCENTERWHMCS/Configuration.php file, the $version string are not upgraded since 2.2.5.

https://github.com/gogetssl/whmcs-addon/blob/v2.2.7/modules/addons/SSLCENTERWHMCS/Configuration.php#L56

**Comment by vlad-evg** [comment]
Shit... sorry guys... 20 min

**Comment by vlad-evg** [comment]
Again sorry for wasting your time. https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.7a

**Comment by vlad-evg** [comment]
New release related to Renewal things coming within 5-7 days, that should solve all renewal issues we talked to all of you

**Comment by w3servicesdotnet** [comment]
OK but please share any workaround steps to handle renewal.

From


*Sunil YFounder & Cloud Solution Architect*
*-----------------------------------------------------------------------*
Tel. +91 9967222267 / 09300670068


<https://members.w3services.net/viewticket.php?tid=233326&c=JBbCobNW&feedback=1>

**Comment by DennisSkov** [comment]
@vlad-evg are you sure the issue is fixed? I've just uploaded the new release and I still see version 2.2.5.

**Comment by vlad-evg** [comment]
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.2.7a

Yes, just tried uploading to our own environment

**Comment by DennisSkov** [comment]
Fuck me. I was uploading it to the wrong WHMCS installation. Fixed!

**Comment by vlad-evg** [comment]
Friday :)
