### ISSUE TITLE
WHMCS Import Order - Unable to create order

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#9]
**Describe the bug**
Within WHMCS GGSSL module the 'Import SSL Order' always says "Unable to create order" when trying to import any order.

**To Reproduce**
1. Go to WHMCS > Addons > GGSSL > Import SSL Order - Unable to create order
2. Add 'API Order ID' and select user
3. Click on 'Import'
4. See error - Unable to create order

**Expected behavior**
SSL Order to be added to client

**Screenshots**
Is this public? 

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**

**Comment by vlad-evg** [comment]
Dear Customer,

Yes, we are aware of that problem, and solution should be released ASAP

**Comment by shabsta** [comment]
Thanks for addressing these issues.
We have been meaning to upgrade to this version but will wait until these fixes have been resolved.
Is there any documentation to migrate from GOGETSSL 1.0.22?

**Comment by qhgh** [comment]
OK thank you, look forward to new update :)

**Comment by qhgh** [comment]
Hi guys, I can confirm that v1.0.39 is working :) thank you!
