### ISSUE TITLE
SSL Renewal Issues - Duplicate Gogetssl orders + more

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#91]
**Describe the bug**
The module is setup to not generate renewal invoices, how ever whmcs' settings automatically generate a renewal invoice for a recurring service.

If this invoice is paid, the module then creates duplicate orders on gogetssl.

**Expected behavior**
If the module is set to not generate renewal invoices then a hook needs to added to ensure that whmcs does not generate an invoice on the next renewal.

Additionally, duplicate orders created on gogetssl need to be investigated.

**Screenshots**
None, more than welcome to reach out via direct email and we can work on the issue - happy to give yourselves and modulesgarden access if required.

**Comment by vlad-evg** [comment]
Much appreciated, we just forwarded that to MG

**Comment by vlad-evg** [comment]
Here is what we got:

"I'm not sure exactly what duplicate orders means. I think you mean that after paying the invoice a new order is created for the next certificate.
When the Renew - New Order field is not checked, the module will not generate an invoice, however the client can do it using the Renew button in ClientArea.
In addition, I will add when the Renew - New Order field is not checked, this does not mean that no further order will be created for a given certificate. This can only happen, however, if you pay for the invoice generated by the module. When the WHMCS invoice is paid, no new order will be created."
