### ISSUE TITLE
Wildcard CSR error not displayed

### ISSUE THREAD

**Issue by charliehu** [gogetssl/whmcs-addon#93]
Hello,

We using v2.2.8

Costumer ordered a Comodo Essential Wildcard SSL certificate. They uploaded CSR, and after when he choosed the validation type, he navigated back to the first step page (where client can upload CSR).

We checked it, and looks like, costumer not added wildcard into CSR (they used domain.tld as common name). 
I enabled module debug, and i also see this error messages as respond for api request:

respond:
`{"error":true,"message":"115","description":"Please submit CSR code using ASTERISK (`*`) in the common name, example: *.domain.com."}`

So, my problem is, why is this error not displayed for the client when he uploaded the CSR? Becaues without error messages he was in an infinite loop basically.

**Comment by vlad-evg** [comment]
Hello,

Thank you. So looks CSR decoder not verified if CSR is wildcard before sending to the 2nd step.
I will report that issue to fix asap

**Comment by charliehu** [comment]
Yes. Or other solution, it have to display the error message what come back
from API.

**Comment by vlad-evg** [comment]
That thing is fixed, will be in next release. Hopefull today
